// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledContainerInterfaceApplyConfiguration represents a declarative configuration of the CompiledContainerInterface type for use
// with apply.
//
// CompiledContainerInterface is a resolved overlay interface for a container.
type CompiledContainerInterfaceApplyConfiguration struct {
	// NetworkName is the multus NetworkAttachmentDefinition name for the overlay binding.
	NetworkName *string `json:"networkName,omitempty"`
	// NetworkInterfaceRef is "<namespace>/<nic>" — the pod's net.ectobase.dev/network-interface
	// annotation, which flowplane-cni resolves to the CompiledNIC.
	NetworkInterfaceRef *string `json:"networkInterfaceRef,omitempty"`
	// MAC is the pinned L2 address (from the NetworkInterface).
	MAC *string `json:"mac,omitempty"`
}

// CompiledContainerInterfaceApplyConfiguration constructs a declarative configuration of the CompiledContainerInterface type for use with
// apply.
func CompiledContainerInterface() *CompiledContainerInterfaceApplyConfiguration {
	return &CompiledContainerInterfaceApplyConfiguration{}
}

// WithNetworkName sets the NetworkName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkName field is set to the value of the last call.
func (b *CompiledContainerInterfaceApplyConfiguration) WithNetworkName(value string) *CompiledContainerInterfaceApplyConfiguration {
	b.NetworkName = &value
	return b
}

// WithNetworkInterfaceRef sets the NetworkInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkInterfaceRef field is set to the value of the last call.
func (b *CompiledContainerInterfaceApplyConfiguration) WithNetworkInterfaceRef(value string) *CompiledContainerInterfaceApplyConfiguration {
	b.NetworkInterfaceRef = &value
	return b
}

// WithMAC sets the MAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MAC field is set to the value of the last call.
func (b *CompiledContainerInterfaceApplyConfiguration) WithMAC(value string) *CompiledContainerInterfaceApplyConfiguration {
	b.MAC = &value
	return b
}
