// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledNATSourceApplyConfiguration represents a declarative configuration of the CompiledNATSource type for use
// with apply.
//
// CompiledNATSource is one egress-SNAT mapping: an overlay source IP SNATed onto a public NAT IP
// and source-port range. It corresponds to a single NATGateway allocation for one of the NIC's IPs.
type CompiledNATSourceApplyConfiguration struct {
	// SourceIP is the overlay IP being SNATed (one of the NIC's OverlayIPs).
	SourceIP *string `json:"sourceIP,omitempty"`
	// NATIP is the public NAT IPv4 address.
	NATIP *string `json:"natIP,omitempty"`
	// PortMin is the start of the source-port range (inclusive).
	PortMin *int32 `json:"portMin,omitempty"`
	// PortMax is the end of the source-port range (inclusive).
	PortMax *int32 `json:"portMax,omitempty"`
}

// CompiledNATSourceApplyConfiguration constructs a declarative configuration of the CompiledNATSource type for use with
// apply.
func CompiledNATSource() *CompiledNATSourceApplyConfiguration {
	return &CompiledNATSourceApplyConfiguration{}
}

// WithSourceIP sets the SourceIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceIP field is set to the value of the last call.
func (b *CompiledNATSourceApplyConfiguration) WithSourceIP(value string) *CompiledNATSourceApplyConfiguration {
	b.SourceIP = &value
	return b
}

// WithNATIP sets the NATIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NATIP field is set to the value of the last call.
func (b *CompiledNATSourceApplyConfiguration) WithNATIP(value string) *CompiledNATSourceApplyConfiguration {
	b.NATIP = &value
	return b
}

// WithPortMin sets the PortMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortMin field is set to the value of the last call.
func (b *CompiledNATSourceApplyConfiguration) WithPortMin(value int32) *CompiledNATSourceApplyConfiguration {
	b.PortMin = &value
	return b
}

// WithPortMax sets the PortMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortMax field is set to the value of the last call.
func (b *CompiledNATSourceApplyConfiguration) WithPortMax(value int32) *CompiledNATSourceApplyConfiguration {
	b.PortMax = &value
	return b
}
