// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledFirewallApplyConfiguration represents a declarative configuration of the CompiledFirewall type for use
// with apply.
//
// CompiledFirewall holds pre-compiled ingress and egress rules for a NIC.
type CompiledFirewallApplyConfiguration struct {
	// Ingress is the ordered list of ingress firewall rules.
	Ingress []CompiledFwRuleApplyConfiguration `json:"ingress,omitempty"`
	// Egress is the ordered list of egress firewall rules.
	Egress []CompiledFwRuleApplyConfiguration `json:"egress,omitempty"`
}

// CompiledFirewallApplyConfiguration constructs a declarative configuration of the CompiledFirewall type for use with
// apply.
func CompiledFirewall() *CompiledFirewallApplyConfiguration {
	return &CompiledFirewallApplyConfiguration{}
}

// WithIngress adds the given value to the Ingress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ingress field.
func (b *CompiledFirewallApplyConfiguration) WithIngress(values ...*CompiledFwRuleApplyConfiguration) *CompiledFirewallApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIngress")
		}
		b.Ingress = append(b.Ingress, *values[i])
	}
	return b
}

// WithEgress adds the given value to the Egress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Egress field.
func (b *CompiledFirewallApplyConfiguration) WithEgress(values ...*CompiledFwRuleApplyConfiguration) *CompiledFirewallApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEgress")
		}
		b.Egress = append(b.Egress, *values[i])
	}
	return b
}
