// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FirewallPolicyRuleApplyConfiguration represents a declarative configuration of the FirewallPolicyRule type for use
// with apply.
//
// FirewallPolicyRule is a single allow/deny rule for ingress or egress traffic.
type FirewallPolicyRuleApplyConfiguration struct {
	// CIDR is the source (ingress) or destination (egress) CIDR to match.
	// "0.0.0.0/0" matches all addresses.
	CIDR *string `json:"cidr,omitempty"`
	// Proto is the IP protocol to match ("TCP", "UDP", "ICMP", or "" for any).
	Proto *string `json:"proto,omitempty"`
	// Port is the destination port to match (0 = any).
	Port *int32 `json:"port,omitempty"`
	// Action is "Allow" or "Deny".
	Action *string `json:"action,omitempty"`
}

// FirewallPolicyRuleApplyConfiguration constructs a declarative configuration of the FirewallPolicyRule type for use with
// apply.
func FirewallPolicyRule() *FirewallPolicyRuleApplyConfiguration {
	return &FirewallPolicyRuleApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *FirewallPolicyRuleApplyConfiguration) WithCIDR(value string) *FirewallPolicyRuleApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithProto sets the Proto field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proto field is set to the value of the last call.
func (b *FirewallPolicyRuleApplyConfiguration) WithProto(value string) *FirewallPolicyRuleApplyConfiguration {
	b.Proto = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *FirewallPolicyRuleApplyConfiguration) WithPort(value int32) *FirewallPolicyRuleApplyConfiguration {
	b.Port = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *FirewallPolicyRuleApplyConfiguration) WithAction(value string) *FirewallPolicyRuleApplyConfiguration {
	b.Action = &value
	return b
}
