// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NATGatewayStatusApplyConfiguration represents a declarative configuration of the NATGatewayStatus type for use
// with apply.
//
// NATGatewayStatus is the observed state.
type NATGatewayStatusApplyConfiguration struct {
	// Allocations is the deterministic source→block table (published to all gateways).
	Allocations []NATAllocationApplyConfiguration `json:"allocations,omitempty"`
	State       *string                           `json:"state,omitempty"`
}

// NATGatewayStatusApplyConfiguration constructs a declarative configuration of the NATGatewayStatus type for use with
// apply.
func NATGatewayStatus() *NATGatewayStatusApplyConfiguration {
	return &NATGatewayStatusApplyConfiguration{}
}

// WithAllocations adds the given value to the Allocations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Allocations field.
func (b *NATGatewayStatusApplyConfiguration) WithAllocations(values ...*NATAllocationApplyConfiguration) *NATGatewayStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllocations")
		}
		b.Allocations = append(b.Allocations, *values[i])
	}
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *NATGatewayStatusApplyConfiguration) WithState(value string) *NATGatewayStatusApplyConfiguration {
	b.State = &value
	return b
}
