// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkInterfaceSpecApplyConfiguration represents a declarative configuration of the NetworkInterfaceSpec type for use
// with apply.
//
// NetworkInterfaceSpec is the desired state of a NetworkInterface (a thin NIC).
type NetworkInterfaceSpecApplyConfiguration struct {
	// VPCRef references the VPC this interface belongs to.
	VPCRef *LocalObjectReferenceApplyConfiguration `json:"vpcRef,omitempty"`
	// IPs are the user-specified overlay IPs (v4 and/or v6). The platform does
	// not allocate these.
	IPs []string `json:"ips,omitempty"`
	// MAC is the interface's L2 address. REQUIRED for a KubeVirt VM (device_type
	// pod-tap/tap): the datapath programs this as the guest MAC, and the VMI's
	// spec.domain.devices.interfaces[].macAddress MUST be set to the same value so
	// KubeVirt gives the VM's virtio NIC that MAC. Empty for containers (derived).
	MAC *string `json:"mac,omitempty"`
	// NodeName is the node the interface is scheduled onto. Set by the scheduler.
	NodeName *string `json:"nodeName,omitempty"`
	// QoS caps/shapes throughput for this interface. Nil = unlimited.
	QoS *InterfaceQoSApplyConfiguration `json:"qos,omitempty"`
	// ClusterName is the compute cluster this standalone (e.g. Pod) NIC targets. The
	// compiler uses it for placement (CompiledNIC.spec.clusterName) when no
	// VirtualMachine owns this NIC; an owning VM's placement takes precedence.
	ClusterName *string `json:"clusterName,omitempty"`
}

// NetworkInterfaceSpecApplyConfiguration constructs a declarative configuration of the NetworkInterfaceSpec type for use with
// apply.
func NetworkInterfaceSpec() *NetworkInterfaceSpecApplyConfiguration {
	return &NetworkInterfaceSpecApplyConfiguration{}
}

// WithVPCRef sets the VPCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPCRef field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithVPCRef(value *LocalObjectReferenceApplyConfiguration) *NetworkInterfaceSpecApplyConfiguration {
	b.VPCRef = value
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *NetworkInterfaceSpecApplyConfiguration) WithIPs(values ...string) *NetworkInterfaceSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithMAC sets the MAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MAC field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithMAC(value string) *NetworkInterfaceSpecApplyConfiguration {
	b.MAC = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithNodeName(value string) *NetworkInterfaceSpecApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithQoS sets the QoS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QoS field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithQoS(value *InterfaceQoSApplyConfiguration) *NetworkInterfaceSpecApplyConfiguration {
	b.QoS = value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *NetworkInterfaceSpecApplyConfiguration) WithClusterName(value string) *NetworkInterfaceSpecApplyConfiguration {
	b.ClusterName = &value
	return b
}
