// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RateLimitApplyConfiguration represents a declarative configuration of the RateLimit type for use
// with apply.
//
// RateLimit is a token-bucket policing cap.
type RateLimitApplyConfiguration struct {
	// RateMbps caps throughput in Mbit/s. 0 = unlimited.
	RateMbps *uint32 `json:"rateMbps,omitempty"`
	// BurstKB is an optional burst allowance in KB. Reserved (default burst in v1). 0 = default.
	BurstKB *uint32 `json:"burstKB,omitempty"`
}

// RateLimitApplyConfiguration constructs a declarative configuration of the RateLimit type for use with
// apply.
func RateLimit() *RateLimitApplyConfiguration {
	return &RateLimitApplyConfiguration{}
}

// WithRateMbps sets the RateMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateMbps field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithRateMbps(value uint32) *RateLimitApplyConfiguration {
	b.RateMbps = &value
	return b
}

// WithBurstKB sets the BurstKB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BurstKB field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithBurstKB(value uint32) *RateLimitApplyConfiguration {
	b.BurstKB = &value
	return b
}
