// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VirtualMachineStatusApplyConfiguration represents a declarative configuration of the VirtualMachineStatus type for use
// with apply.
//
// VirtualMachineStatus defines the observed state of a VirtualMachine.
type VirtualMachineStatusApplyConfiguration struct {
	// Phase is the current lifecycle phase of the VirtualMachine.
	Phase *string `json:"phase,omitempty"`
	// Conditions capture scheduling/failover observations (Scheduled, Unschedulable, FailoverBlocked).
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Placement is the VM's actual running location, stamped by the broker. Central
	// uses NodePrefix as the fence coordinate and to gate recovery drain.
	Placement *VMPlacementApplyConfiguration `json:"placement,omitempty"`
}

// VirtualMachineStatusApplyConfiguration constructs a declarative configuration of the VirtualMachineStatus type for use with
// apply.
func VirtualMachineStatus() *VirtualMachineStatusApplyConfiguration {
	return &VirtualMachineStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *VirtualMachineStatusApplyConfiguration) WithPhase(value string) *VirtualMachineStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VirtualMachineStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *VirtualMachineStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithPlacement sets the Placement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Placement field is set to the value of the last call.
func (b *VirtualMachineStatusApplyConfiguration) WithPlacement(value *VMPlacementApplyConfiguration) *VirtualMachineStatusApplyConfiguration {
	b.Placement = value
	return b
}
