// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VMPlacementApplyConfiguration represents a declarative configuration of the VMPlacement type for use
// with apply.
//
// VMPlacement is the VM's actual running location, reported upward by the broker.
type VMPlacementApplyConfiguration struct {
	// ClusterName is the pool the VM is running on.
	ClusterName *string `json:"clusterName,omitempty"`
	// NodeName is the node running the VM.
	NodeName *string `json:"nodeName,omitempty"`
	// NodePrefix is that node's /64 underlay prefix (the fence coordinate).
	NodePrefix *string `json:"nodePrefix,omitempty"`
}

// VMPlacementApplyConfiguration constructs a declarative configuration of the VMPlacement type for use with
// apply.
func VMPlacement() *VMPlacementApplyConfiguration {
	return &VMPlacementApplyConfiguration{}
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *VMPlacementApplyConfiguration) WithClusterName(value string) *VMPlacementApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *VMPlacementApplyConfiguration) WithNodeName(value string) *VMPlacementApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithNodePrefix sets the NodePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePrefix field is set to the value of the last call.
func (b *VMPlacementApplyConfiguration) WithNodePrefix(value string) *VMPlacementApplyConfiguration {
	b.NodePrefix = &value
	return b
}
