// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VolumeStatusApplyConfiguration represents a declarative configuration of the VolumeStatus type for use
// with apply.
//
// VolumeStatus is the observed state of a Volume.
type VolumeStatusApplyConfiguration struct {
	// Phase is the current lifecycle phase of the Volume.
	Phase *string `json:"phase,omitempty"`
}

// VolumeStatusApplyConfiguration constructs a declarative configuration of the VolumeStatus type for use with
// apply.
func VolumeStatus() *VolumeStatusApplyConfiguration {
	return &VolumeStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithPhase(value string) *VolumeStatusApplyConfiguration {
	b.Phase = &value
	return b
}
