// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EgressQoSApplyConfiguration represents a declarative configuration of the EgressQoS type for use
// with apply.
//
// EgressQoS shapes total egress (EDT) with an optional external sub-cap.
type EgressQoSApplyConfiguration struct {
	// RateMbps is the EDT-shaped total egress rate in Mbit/s. 0 = unlimited.
	RateMbps *uint32 `json:"rateMbps,omitempty"`
	// BurstKB is an optional burst allowance in KB. Reserved (EDT ignores it in v1). 0 = default.
	BurstKB *uint32 `json:"burstKB,omitempty"`
	// PublicMbps caps external/NATed egress in Mbit/s (policed). 0 = unlimited.
	PublicMbps *uint32 `json:"publicMbps,omitempty"`
}

// EgressQoSApplyConfiguration constructs a declarative configuration of the EgressQoS type for use with
// apply.
func EgressQoS() *EgressQoSApplyConfiguration {
	return &EgressQoSApplyConfiguration{}
}

// WithRateMbps sets the RateMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateMbps field is set to the value of the last call.
func (b *EgressQoSApplyConfiguration) WithRateMbps(value uint32) *EgressQoSApplyConfiguration {
	b.RateMbps = &value
	return b
}

// WithBurstKB sets the BurstKB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BurstKB field is set to the value of the last call.
func (b *EgressQoSApplyConfiguration) WithBurstKB(value uint32) *EgressQoSApplyConfiguration {
	b.BurstKB = &value
	return b
}

// WithPublicMbps sets the PublicMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicMbps field is set to the value of the last call.
func (b *EgressQoSApplyConfiguration) WithPublicMbps(value uint32) *EgressQoSApplyConfiguration {
	b.PublicMbps = &value
	return b
}
