// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NATAllocationApplyConfiguration represents a declarative configuration of the NATAllocation type for use
// with apply.
//
// NATAllocation records one source's deterministic mapping.
type NATAllocationApplyConfiguration struct {
	// Source is the overlay IP (a NetworkInterface IP) being SNATed.
	Source *string `json:"source,omitempty"`
	// PublicIP + [PortMin,PortMax] is the deterministic block.
	PublicIP *string `json:"publicIP,omitempty"`
	PortMin  *int32  `json:"portMin,omitempty"`
	PortMax  *int32  `json:"portMax,omitempty"`
}

// NATAllocationApplyConfiguration constructs a declarative configuration of the NATAllocation type for use with
// apply.
func NATAllocation() *NATAllocationApplyConfiguration {
	return &NATAllocationApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *NATAllocationApplyConfiguration) WithSource(value string) *NATAllocationApplyConfiguration {
	b.Source = &value
	return b
}

// WithPublicIP sets the PublicIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicIP field is set to the value of the last call.
func (b *NATAllocationApplyConfiguration) WithPublicIP(value string) *NATAllocationApplyConfiguration {
	b.PublicIP = &value
	return b
}

// WithPortMin sets the PortMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortMin field is set to the value of the last call.
func (b *NATAllocationApplyConfiguration) WithPortMin(value int32) *NATAllocationApplyConfiguration {
	b.PortMin = &value
	return b
}

// WithPortMax sets the PortMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortMax field is set to the value of the last call.
func (b *NATAllocationApplyConfiguration) WithPortMax(value int32) *NATAllocationApplyConfiguration {
	b.PortMax = &value
	return b
}
