// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NATGatewaySpecApplyConfiguration represents a declarative configuration of the NATGatewaySpec type for use
// with apply.
//
// NATGatewaySpec is the desired state of a NATGateway: a drain-safe egress SNAT
// for the sources in a VPC, using deterministic (public-IP, port-block) allocation.
type NATGatewaySpecApplyConfiguration struct {
	// VPCRef selects the VPC whose interfaces egress through this gateway.
	VPCRef *LocalObjectReferenceApplyConfiguration `json:"vpcRef,omitempty"`
	// PublicIPs is the pool of public IPv4s SNAT sources are mapped onto.
	PublicIPs []string `json:"publicIPs,omitempty"`
	// PortsPerSource is the deterministic port-block size handed to each source
	// (RFC 7422 / GCP-static style). Default 1024.
	PortsPerSource *int32 `json:"portsPerSource,omitempty"`
	// EdgeUnderlay is DEPRECATED and IGNORED. The edge fleet self-advertises via
	// EDGE_UNDERLAY: egress (0.0.0.0/0 and 64:ff9b::/96 for NAT64) is originated by
	// any agent started with --edge-loopback, nexthop'd at that edge's own anycast
	// underlay. Retained only to avoid a CRD breaking change; set nothing here.
	EdgeUnderlay *string `json:"edgeUnderlay,omitempty"`
}

// NATGatewaySpecApplyConfiguration constructs a declarative configuration of the NATGatewaySpec type for use with
// apply.
func NATGatewaySpec() *NATGatewaySpecApplyConfiguration {
	return &NATGatewaySpecApplyConfiguration{}
}

// WithVPCRef sets the VPCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPCRef field is set to the value of the last call.
func (b *NATGatewaySpecApplyConfiguration) WithVPCRef(value *LocalObjectReferenceApplyConfiguration) *NATGatewaySpecApplyConfiguration {
	b.VPCRef = value
	return b
}

// WithPublicIPs adds the given value to the PublicIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PublicIPs field.
func (b *NATGatewaySpecApplyConfiguration) WithPublicIPs(values ...string) *NATGatewaySpecApplyConfiguration {
	for i := range values {
		b.PublicIPs = append(b.PublicIPs, values[i])
	}
	return b
}

// WithPortsPerSource sets the PortsPerSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortsPerSource field is set to the value of the last call.
func (b *NATGatewaySpecApplyConfiguration) WithPortsPerSource(value int32) *NATGatewaySpecApplyConfiguration {
	b.PortsPerSource = &value
	return b
}

// WithEdgeUnderlay sets the EdgeUnderlay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EdgeUnderlay field is set to the value of the last call.
func (b *NATGatewaySpecApplyConfiguration) WithEdgeUnderlay(value string) *NATGatewaySpecApplyConfiguration {
	b.EdgeUnderlay = &value
	return b
}
