//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	platform "github.com/trevex/ectobase/api/platform"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterPool)(nil), (*platform.ClusterPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPool_To_platform_ClusterPool(a.(*ClusterPool), b.(*platform.ClusterPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPool)(nil), (*ClusterPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPool_To_v1alpha1_ClusterPool(a.(*platform.ClusterPool), b.(*ClusterPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolLease)(nil), (*platform.ClusterPoolLease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(a.(*ClusterPoolLease), b.(*platform.ClusterPoolLease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolLease)(nil), (*ClusterPoolLease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(a.(*platform.ClusterPoolLease), b.(*ClusterPoolLease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolList)(nil), (*platform.ClusterPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(a.(*ClusterPoolList), b.(*platform.ClusterPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolList)(nil), (*ClusterPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(a.(*platform.ClusterPoolList), b.(*ClusterPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolSpec)(nil), (*platform.ClusterPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(a.(*ClusterPoolSpec), b.(*platform.ClusterPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolSpec)(nil), (*ClusterPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(a.(*platform.ClusterPoolSpec), b.(*ClusterPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolStatus)(nil), (*platform.ClusterPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(a.(*ClusterPoolStatus), b.(*platform.ClusterPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolStatus)(nil), (*ClusterPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(a.(*platform.ClusterPoolStatus), b.(*ClusterPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeDrainStatus)(nil), (*platform.NodeDrainStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeDrainStatus_To_platform_NodeDrainStatus(a.(*NodeDrainStatus), b.(*platform.NodeDrainStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.NodeDrainStatus)(nil), (*NodeDrainStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_NodeDrainStatus_To_v1alpha1_NodeDrainStatus(a.(*platform.NodeDrainStatus), b.(*NodeDrainStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteBusIdentity)(nil), (*platform.RouteBusIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteBusIdentity_To_platform_RouteBusIdentity(a.(*RouteBusIdentity), b.(*platform.RouteBusIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.RouteBusIdentity)(nil), (*RouteBusIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_RouteBusIdentity_To_v1alpha1_RouteBusIdentity(a.(*platform.RouteBusIdentity), b.(*RouteBusIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteBusIdentityList)(nil), (*platform.RouteBusIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteBusIdentityList_To_platform_RouteBusIdentityList(a.(*RouteBusIdentityList), b.(*platform.RouteBusIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.RouteBusIdentityList)(nil), (*RouteBusIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_RouteBusIdentityList_To_v1alpha1_RouteBusIdentityList(a.(*platform.RouteBusIdentityList), b.(*RouteBusIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteBusIdentitySpec)(nil), (*platform.RouteBusIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec(a.(*RouteBusIdentitySpec), b.(*platform.RouteBusIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.RouteBusIdentitySpec)(nil), (*RouteBusIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec(a.(*platform.RouteBusIdentitySpec), b.(*RouteBusIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteBusIdentityStatus)(nil), (*platform.RouteBusIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus(a.(*RouteBusIdentityStatus), b.(*platform.RouteBusIdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.RouteBusIdentityStatus)(nil), (*RouteBusIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus(a.(*platform.RouteBusIdentityStatus), b.(*RouteBusIdentityStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterPool_To_platform_ClusterPool(in *ClusterPool, out *platform.ClusterPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterPool_To_platform_ClusterPool is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPool_To_platform_ClusterPool(in *ClusterPool, out *platform.ClusterPool, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPool_To_platform_ClusterPool(in, out, s)
}

func autoConvert_platform_ClusterPool_To_v1alpha1_ClusterPool(in *platform.ClusterPool, out *ClusterPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_platform_ClusterPool_To_v1alpha1_ClusterPool is an autogenerated conversion function.
func Convert_platform_ClusterPool_To_v1alpha1_ClusterPool(in *platform.ClusterPool, out *ClusterPool, s conversion.Scope) error {
	return autoConvert_platform_ClusterPool_To_v1alpha1_ClusterPool(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in *ClusterPoolLease, out *platform.ClusterPoolLease, s conversion.Scope) error {
	out.HolderIdentity = in.HolderIdentity
	out.RenewTime = (*v1.MicroTime)(unsafe.Pointer(in.RenewTime))
	return nil
}

// Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in *ClusterPoolLease, out *platform.ClusterPoolLease, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in, out, s)
}

func autoConvert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in *platform.ClusterPoolLease, out *ClusterPoolLease, s conversion.Scope) error {
	out.HolderIdentity = in.HolderIdentity
	out.RenewTime = (*v1.MicroTime)(unsafe.Pointer(in.RenewTime))
	return nil
}

// Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease is an autogenerated conversion function.
func Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in *platform.ClusterPoolLease, out *ClusterPoolLease, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in *ClusterPoolList, out *platform.ClusterPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]platform.ClusterPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in *ClusterPoolList, out *platform.ClusterPoolList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in, out, s)
}

func autoConvert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in *platform.ClusterPoolList, out *ClusterPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList is an autogenerated conversion function.
func Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in *platform.ClusterPoolList, out *ClusterPoolList, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in *ClusterPoolSpec, out *platform.ClusterPoolSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.Endpoint = in.Endpoint
	return nil
}

// Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in *ClusterPoolSpec, out *platform.ClusterPoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in, out, s)
}

func autoConvert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in *platform.ClusterPoolSpec, out *ClusterPoolSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.Endpoint = in.Endpoint
	return nil
}

// Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec is an autogenerated conversion function.
func Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in *platform.ClusterPoolSpec, out *ClusterPoolSpec, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in *ClusterPoolStatus, out *platform.ClusterPoolStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.Allocatable = *(*corev1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Lease = (*platform.ClusterPoolLease)(unsafe.Pointer(in.Lease))
	out.NodePrefixes = *(*[]string)(unsafe.Pointer(&in.NodePrefixes))
	out.FencedPrefixes = *(*[]string)(unsafe.Pointer(&in.FencedPrefixes))
	out.NodeDrain = *(*[]platform.NodeDrainStatus)(unsafe.Pointer(&in.NodeDrain))
	return nil
}

// Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in *ClusterPoolStatus, out *platform.ClusterPoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in, out, s)
}

func autoConvert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in *platform.ClusterPoolStatus, out *ClusterPoolStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.Allocatable = *(*corev1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Lease = (*ClusterPoolLease)(unsafe.Pointer(in.Lease))
	out.NodePrefixes = *(*[]string)(unsafe.Pointer(&in.NodePrefixes))
	out.FencedPrefixes = *(*[]string)(unsafe.Pointer(&in.FencedPrefixes))
	out.NodeDrain = *(*[]NodeDrainStatus)(unsafe.Pointer(&in.NodeDrain))
	return nil
}

// Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus is an autogenerated conversion function.
func Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in *platform.ClusterPoolStatus, out *ClusterPoolStatus, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeDrainStatus_To_platform_NodeDrainStatus(in *NodeDrainStatus, out *platform.NodeDrainStatus, s conversion.Scope) error {
	out.Prefix = in.Prefix
	out.Drained = in.Drained
	return nil
}

// Convert_v1alpha1_NodeDrainStatus_To_platform_NodeDrainStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeDrainStatus_To_platform_NodeDrainStatus(in *NodeDrainStatus, out *platform.NodeDrainStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeDrainStatus_To_platform_NodeDrainStatus(in, out, s)
}

func autoConvert_platform_NodeDrainStatus_To_v1alpha1_NodeDrainStatus(in *platform.NodeDrainStatus, out *NodeDrainStatus, s conversion.Scope) error {
	out.Prefix = in.Prefix
	out.Drained = in.Drained
	return nil
}

// Convert_platform_NodeDrainStatus_To_v1alpha1_NodeDrainStatus is an autogenerated conversion function.
func Convert_platform_NodeDrainStatus_To_v1alpha1_NodeDrainStatus(in *platform.NodeDrainStatus, out *NodeDrainStatus, s conversion.Scope) error {
	return autoConvert_platform_NodeDrainStatus_To_v1alpha1_NodeDrainStatus(in, out, s)
}

func autoConvert_v1alpha1_RouteBusIdentity_To_platform_RouteBusIdentity(in *RouteBusIdentity, out *platform.RouteBusIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RouteBusIdentity_To_platform_RouteBusIdentity is an autogenerated conversion function.
func Convert_v1alpha1_RouteBusIdentity_To_platform_RouteBusIdentity(in *RouteBusIdentity, out *platform.RouteBusIdentity, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteBusIdentity_To_platform_RouteBusIdentity(in, out, s)
}

func autoConvert_platform_RouteBusIdentity_To_v1alpha1_RouteBusIdentity(in *platform.RouteBusIdentity, out *RouteBusIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_platform_RouteBusIdentity_To_v1alpha1_RouteBusIdentity is an autogenerated conversion function.
func Convert_platform_RouteBusIdentity_To_v1alpha1_RouteBusIdentity(in *platform.RouteBusIdentity, out *RouteBusIdentity, s conversion.Scope) error {
	return autoConvert_platform_RouteBusIdentity_To_v1alpha1_RouteBusIdentity(in, out, s)
}

func autoConvert_v1alpha1_RouteBusIdentityList_To_platform_RouteBusIdentityList(in *RouteBusIdentityList, out *platform.RouteBusIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]platform.RouteBusIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RouteBusIdentityList_To_platform_RouteBusIdentityList is an autogenerated conversion function.
func Convert_v1alpha1_RouteBusIdentityList_To_platform_RouteBusIdentityList(in *RouteBusIdentityList, out *platform.RouteBusIdentityList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteBusIdentityList_To_platform_RouteBusIdentityList(in, out, s)
}

func autoConvert_platform_RouteBusIdentityList_To_v1alpha1_RouteBusIdentityList(in *platform.RouteBusIdentityList, out *RouteBusIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RouteBusIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_platform_RouteBusIdentityList_To_v1alpha1_RouteBusIdentityList is an autogenerated conversion function.
func Convert_platform_RouteBusIdentityList_To_v1alpha1_RouteBusIdentityList(in *platform.RouteBusIdentityList, out *RouteBusIdentityList, s conversion.Scope) error {
	return autoConvert_platform_RouteBusIdentityList_To_v1alpha1_RouteBusIdentityList(in, out, s)
}

func autoConvert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec(in *RouteBusIdentitySpec, out *platform.RouteBusIdentitySpec, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.Request = *(*[]byte)(unsafe.Pointer(&in.Request))
	return nil
}

// Convert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec is an autogenerated conversion function.
func Convert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec(in *RouteBusIdentitySpec, out *platform.RouteBusIdentitySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteBusIdentitySpec_To_platform_RouteBusIdentitySpec(in, out, s)
}

func autoConvert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec(in *platform.RouteBusIdentitySpec, out *RouteBusIdentitySpec, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.Request = *(*[]byte)(unsafe.Pointer(&in.Request))
	return nil
}

// Convert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec is an autogenerated conversion function.
func Convert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec(in *platform.RouteBusIdentitySpec, out *RouteBusIdentitySpec, s conversion.Scope) error {
	return autoConvert_platform_RouteBusIdentitySpec_To_v1alpha1_RouteBusIdentitySpec(in, out, s)
}

func autoConvert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus(in *RouteBusIdentityStatus, out *platform.RouteBusIdentityStatus, s conversion.Scope) error {
	out.Certificate = *(*[]byte)(unsafe.Pointer(&in.Certificate))
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus is an autogenerated conversion function.
func Convert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus(in *RouteBusIdentityStatus, out *platform.RouteBusIdentityStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteBusIdentityStatus_To_platform_RouteBusIdentityStatus(in, out, s)
}

func autoConvert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus(in *platform.RouteBusIdentityStatus, out *RouteBusIdentityStatus, s conversion.Scope) error {
	out.Certificate = *(*[]byte)(unsafe.Pointer(&in.Certificate))
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus is an autogenerated conversion function.
func Convert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus(in *platform.RouteBusIdentityStatus, out *RouteBusIdentityStatus, s conversion.Scope) error {
	return autoConvert_platform_RouteBusIdentityStatus_To_v1alpha1_RouteBusIdentityStatus(in, out, s)
}
