//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPool) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolLease) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolLease"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolList) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolSpec) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolStatus) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeDrainStatus) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.NodeDrainStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteBusIdentity) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.RouteBusIdentity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteBusIdentityList) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.RouteBusIdentityList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteBusIdentitySpec) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.RouteBusIdentitySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteBusIdentityStatus) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.RouteBusIdentityStatus"
}
