//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ClusterPool{}, func(obj interface{}) { SetObjectDefaults_ClusterPool(obj.(*ClusterPool)) })
	scheme.AddTypeDefaultingFunc(&ClusterPoolList{}, func(obj interface{}) { SetObjectDefaults_ClusterPoolList(obj.(*ClusterPoolList)) })
	return nil
}

func SetObjectDefaults_ClusterPool(in *ClusterPool) {
	SetDefaults_ClusterPoolSpec(&in.Spec)
}

func SetObjectDefaults_ClusterPoolList(in *ClusterPoolList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ClusterPool(a)
	}
}
