// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/central/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVolumes implements VolumeInterface
type fakeVolumes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Volume, *v1alpha1.VolumeList, *netv1alpha1.VolumeApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeVolumes(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.VolumeInterface {
	return &fakeVolumes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Volume, *v1alpha1.VolumeList, *netv1alpha1.VolumeApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("volumes"),
			v1alpha1.SchemeGroupVersion.WithKind("Volume"),
			func() *v1alpha1.Volume { return &v1alpha1.Volume{} },
			func() *v1alpha1.VolumeList { return &v1alpha1.VolumeList{} },
			func(dst, src *v1alpha1.VolumeList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VolumeList) []*v1alpha1.Volume { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VolumeList, items []*v1alpha1.Volume) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
