// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/central/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCompiledVolumeAttachments implements CompiledVolumeAttachmentInterface
type fakeCompiledVolumeAttachments struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.CompiledVolumeAttachment, *v1alpha1.CompiledVolumeAttachmentList, *netv1alpha1.CompiledVolumeAttachmentApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeCompiledVolumeAttachments(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.CompiledVolumeAttachmentInterface {
	return &fakeCompiledVolumeAttachments{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.CompiledVolumeAttachment, *v1alpha1.CompiledVolumeAttachmentList, *netv1alpha1.CompiledVolumeAttachmentApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("compiledvolumeattachments"),
			v1alpha1.SchemeGroupVersion.WithKind("CompiledVolumeAttachment"),
			func() *v1alpha1.CompiledVolumeAttachment { return &v1alpha1.CompiledVolumeAttachment{} },
			func() *v1alpha1.CompiledVolumeAttachmentList { return &v1alpha1.CompiledVolumeAttachmentList{} },
			func(dst, src *v1alpha1.CompiledVolumeAttachmentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CompiledVolumeAttachmentList) []*v1alpha1.CompiledVolumeAttachment {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CompiledVolumeAttachmentList, items []*v1alpha1.CompiledVolumeAttachment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
