// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/central/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFirewallPolicies implements FirewallPolicyInterface
type fakeFirewallPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.FirewallPolicy, *v1alpha1.FirewallPolicyList, *netv1alpha1.FirewallPolicyApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeFirewallPolicies(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.FirewallPolicyInterface {
	return &fakeFirewallPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.FirewallPolicy, *v1alpha1.FirewallPolicyList, *netv1alpha1.FirewallPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("firewallpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("FirewallPolicy"),
			func() *v1alpha1.FirewallPolicy { return &v1alpha1.FirewallPolicy{} },
			func() *v1alpha1.FirewallPolicyList { return &v1alpha1.FirewallPolicyList{} },
			func(dst, src *v1alpha1.FirewallPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FirewallPolicyList) []*v1alpha1.FirewallPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.FirewallPolicyList, items []*v1alpha1.FirewallPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
