// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ContainerListerExpansion allows custom methods to be added to
// ContainerLister.
type ContainerListerExpansion interface{}

// ContainerNamespaceListerExpansion allows custom methods to be added to
// ContainerNamespaceLister.
type ContainerNamespaceListerExpansion interface{}

// FirewallPolicyListerExpansion allows custom methods to be added to
// FirewallPolicyLister.
type FirewallPolicyListerExpansion interface{}

// FirewallPolicyNamespaceListerExpansion allows custom methods to be added to
// FirewallPolicyNamespaceLister.
type FirewallPolicyNamespaceListerExpansion interface{}

// FloatingIPListerExpansion allows custom methods to be added to
// FloatingIPLister.
type FloatingIPListerExpansion interface{}

// FloatingIPNamespaceListerExpansion allows custom methods to be added to
// FloatingIPNamespaceLister.
type FloatingIPNamespaceListerExpansion interface{}

// LoadBalancerListerExpansion allows custom methods to be added to
// LoadBalancerLister.
type LoadBalancerListerExpansion interface{}

// LoadBalancerNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerNamespaceLister.
type LoadBalancerNamespaceListerExpansion interface{}

// NATGatewayListerExpansion allows custom methods to be added to
// NATGatewayLister.
type NATGatewayListerExpansion interface{}

// NATGatewayNamespaceListerExpansion allows custom methods to be added to
// NATGatewayNamespaceLister.
type NATGatewayNamespaceListerExpansion interface{}

// NetworkInterfaceListerExpansion allows custom methods to be added to
// NetworkInterfaceLister.
type NetworkInterfaceListerExpansion interface{}

// NetworkInterfaceNamespaceListerExpansion allows custom methods to be added to
// NetworkInterfaceNamespaceLister.
type NetworkInterfaceNamespaceListerExpansion interface{}

// VPCListerExpansion allows custom methods to be added to
// VPCLister.
type VPCListerExpansion interface{}

// VPCNamespaceListerExpansion allows custom methods to be added to
// VPCNamespaceLister.
type VPCNamespaceListerExpansion interface{}

// VPCPeeringListerExpansion allows custom methods to be added to
// VPCPeeringLister.
type VPCPeeringListerExpansion interface{}

// VPCPeeringNamespaceListerExpansion allows custom methods to be added to
// VPCPeeringNamespaceLister.
type VPCPeeringNamespaceListerExpansion interface{}

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}

// VolumeListerExpansion allows custom methods to be added to
// VolumeLister.
type VolumeListerExpansion interface{}

// VolumeNamespaceListerExpansion allows custom methods to be added to
// VolumeNamespaceLister.
type VolumeNamespaceListerExpansion interface{}
