// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NATGatewayLister helps list NATGateways.
// All objects returned here must be treated as read-only.
type NATGatewayLister interface {
	// List lists all NATGateways in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netv1alpha1.NATGateway, err error)
	// NATGateways returns an object that can list and get NATGateways.
	NATGateways(namespace string) NATGatewayNamespaceLister
	NATGatewayListerExpansion
}

// nATGatewayLister implements the NATGatewayLister interface.
type nATGatewayLister struct {
	listers.ResourceIndexer[*netv1alpha1.NATGateway]
}

// NewNATGatewayLister returns a new NATGatewayLister.
func NewNATGatewayLister(indexer cache.Indexer) NATGatewayLister {
	return &nATGatewayLister{listers.New[*netv1alpha1.NATGateway](indexer, netv1alpha1.Resource("natgateway"))}
}

// NATGateways returns an object that can list and get NATGateways.
func (s *nATGatewayLister) NATGateways(namespace string) NATGatewayNamespaceLister {
	return nATGatewayNamespaceLister{listers.NewNamespaced[*netv1alpha1.NATGateway](s.ResourceIndexer, namespace)}
}

// NATGatewayNamespaceLister helps list and get NATGateways.
// All objects returned here must be treated as read-only.
type NATGatewayNamespaceLister interface {
	// List lists all NATGateways in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netv1alpha1.NATGateway, err error)
	// Get retrieves the NATGateway from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netv1alpha1.NATGateway, error)
	NATGatewayNamespaceListerExpansion
}

// nATGatewayNamespaceLister implements the NATGatewayNamespaceLister
// interface.
type nATGatewayNamespaceLister struct {
	listers.ResourceIndexer[*netv1alpha1.NATGateway]
}
