// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	compiledv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/compiled/v1alpha1"
	typedcompiledv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/compiled/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCompiledContainers implements CompiledContainerInterface
type fakeCompiledContainers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.CompiledContainer, *v1alpha1.CompiledContainerList, *compiledv1alpha1.CompiledContainerApplyConfiguration]
	Fake *FakeCompiledV1alpha1
}

func newFakeCompiledContainers(fake *FakeCompiledV1alpha1, namespace string) typedcompiledv1alpha1.CompiledContainerInterface {
	return &fakeCompiledContainers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.CompiledContainer, *v1alpha1.CompiledContainerList, *compiledv1alpha1.CompiledContainerApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("compiledcontainers"),
			v1alpha1.SchemeGroupVersion.WithKind("CompiledContainer"),
			func() *v1alpha1.CompiledContainer { return &v1alpha1.CompiledContainer{} },
			func() *v1alpha1.CompiledContainerList { return &v1alpha1.CompiledContainerList{} },
			func(dst, src *v1alpha1.CompiledContainerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CompiledContainerList) []*v1alpha1.CompiledContainer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CompiledContainerList, items []*v1alpha1.CompiledContainer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
