// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	compiledv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/compiled/v1alpha1"
	typedcompiledv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/compiled/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCompiledVMs implements CompiledVMInterface
type fakeCompiledVMs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.CompiledVM, *v1alpha1.CompiledVMList, *compiledv1alpha1.CompiledVMApplyConfiguration]
	Fake *FakeCompiledV1alpha1
}

func newFakeCompiledVMs(fake *FakeCompiledV1alpha1, namespace string) typedcompiledv1alpha1.CompiledVMInterface {
	return &fakeCompiledVMs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.CompiledVM, *v1alpha1.CompiledVMList, *compiledv1alpha1.CompiledVMApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("compiledvms"),
			v1alpha1.SchemeGroupVersion.WithKind("CompiledVM"),
			func() *v1alpha1.CompiledVM { return &v1alpha1.CompiledVM{} },
			func() *v1alpha1.CompiledVMList { return &v1alpha1.CompiledVMList{} },
			func(dst, src *v1alpha1.CompiledVMList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CompiledVMList) []*v1alpha1.CompiledVM { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.CompiledVMList, items []*v1alpha1.CompiledVM) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
