// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFloatingIPs implements FloatingIPInterface
type fakeFloatingIPs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.FloatingIP, *v1alpha1.FloatingIPList, *netv1alpha1.FloatingIPApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeFloatingIPs(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.FloatingIPInterface {
	return &fakeFloatingIPs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.FloatingIP, *v1alpha1.FloatingIPList, *netv1alpha1.FloatingIPApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("floatingips"),
			v1alpha1.SchemeGroupVersion.WithKind("FloatingIP"),
			func() *v1alpha1.FloatingIP { return &v1alpha1.FloatingIP{} },
			func() *v1alpha1.FloatingIPList { return &v1alpha1.FloatingIPList{} },
			func(dst, src *v1alpha1.FloatingIPList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FloatingIPList) []*v1alpha1.FloatingIP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.FloatingIPList, items []*v1alpha1.FloatingIP) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
