// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNATGateways implements NATGatewayInterface
type fakeNATGateways struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NATGateway, *v1alpha1.NATGatewayList, *netv1alpha1.NATGatewayApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeNATGateways(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.NATGatewayInterface {
	return &fakeNATGateways{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NATGateway, *v1alpha1.NATGatewayList, *netv1alpha1.NATGatewayApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("natgateways"),
			v1alpha1.SchemeGroupVersion.WithKind("NATGateway"),
			func() *v1alpha1.NATGateway { return &v1alpha1.NATGateway{} },
			func() *v1alpha1.NATGatewayList { return &v1alpha1.NATGatewayList{} },
			func(dst, src *v1alpha1.NATGatewayList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NATGatewayList) []*v1alpha1.NATGateway { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NATGatewayList, items []*v1alpha1.NATGateway) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
