// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeLoadBalancers implements LoadBalancerInterface
type fakeLoadBalancers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.LoadBalancer, *v1alpha1.LoadBalancerList, *netv1alpha1.LoadBalancerApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeLoadBalancers(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.LoadBalancerInterface {
	return &fakeLoadBalancers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.LoadBalancer, *v1alpha1.LoadBalancerList, *netv1alpha1.LoadBalancerApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("loadbalancers"),
			v1alpha1.SchemeGroupVersion.WithKind("LoadBalancer"),
			func() *v1alpha1.LoadBalancer { return &v1alpha1.LoadBalancer{} },
			func() *v1alpha1.LoadBalancerList { return &v1alpha1.LoadBalancerList{} },
			func(dst, src *v1alpha1.LoadBalancerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.LoadBalancerList) []*v1alpha1.LoadBalancer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.LoadBalancerList, items []*v1alpha1.LoadBalancer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
