// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/net/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNetV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNetV1alpha1) FirewallPolicies(namespace string) v1alpha1.FirewallPolicyInterface {
	return newFakeFirewallPolicies(c, namespace)
}

func (c *FakeNetV1alpha1) FloatingIPs(namespace string) v1alpha1.FloatingIPInterface {
	return newFakeFloatingIPs(c, namespace)
}

func (c *FakeNetV1alpha1) LoadBalancers(namespace string) v1alpha1.LoadBalancerInterface {
	return newFakeLoadBalancers(c, namespace)
}

func (c *FakeNetV1alpha1) NATGateways(namespace string) v1alpha1.NATGatewayInterface {
	return newFakeNATGateways(c, namespace)
}

func (c *FakeNetV1alpha1) NetworkInterfaces(namespace string) v1alpha1.NetworkInterfaceInterface {
	return newFakeNetworkInterfaces(c, namespace)
}

func (c *FakeNetV1alpha1) VPCs(namespace string) v1alpha1.VPCInterface {
	return newFakeVPCs(c, namespace)
}

func (c *FakeNetV1alpha1) VPCPeerings(namespace string) v1alpha1.VPCPeeringInterface {
	return newFakeVPCPeerings(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNetV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
