// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CloudInitApplyConfiguration represents a declarative configuration of the CloudInit type for use
// with apply.
//
// CloudInit is guest bootstrap config for a compiled VM, delivered by the materializer
// as a cloud-init NoCloud datasource.
type CloudInitApplyConfiguration struct {
	// UserData is the cloud-init user-data (commonly a #cloud-config document).
	UserData *string `json:"userData,omitempty"`
}

// CloudInitApplyConfiguration constructs a declarative configuration of the CloudInit type for use with
// apply.
func CloudInit() *CloudInitApplyConfiguration {
	return &CloudInitApplyConfiguration{}
}

// WithUserData sets the UserData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserData field is set to the value of the last call.
func (b *CloudInitApplyConfiguration) WithUserData(value string) *CloudInitApplyConfiguration {
	b.UserData = &value
	return b
}
