// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledVolumeAttachmentStatusApplyConfiguration represents a declarative configuration of the CompiledVolumeAttachmentStatus type for use
// with apply.
//
// CompiledVolumeAttachmentStatus is the observed state.
type CompiledVolumeAttachmentStatusApplyConfiguration struct {
	// State is the materialization state.
	State *string `json:"state,omitempty"`
}

// CompiledVolumeAttachmentStatusApplyConfiguration constructs a declarative configuration of the CompiledVolumeAttachmentStatus type for use with
// apply.
func CompiledVolumeAttachmentStatus() *CompiledVolumeAttachmentStatusApplyConfiguration {
	return &CompiledVolumeAttachmentStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CompiledVolumeAttachmentStatusApplyConfiguration) WithState(value string) *CompiledVolumeAttachmentStatusApplyConfiguration {
	b.State = &value
	return b
}
