// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledQoSApplyConfiguration represents a declarative configuration of the CompiledQoS type for use
// with apply.
//
// CompiledQoS holds the flattened per-interface QoS caps in Mbit/s (0 = unlimited) that the
// dataplane programs: egress is EDT-shaped, public caps external/NATed egress, ingress is policed.
type CompiledQoSApplyConfiguration struct {
	// EgressMbps is the total egress EDT shaping cap (0 = unlimited).
	EgressMbps *uint32 `json:"egressMbps,omitempty"`
	// PublicMbps caps external/NATed egress only (0 = unlimited).
	PublicMbps *uint32 `json:"publicMbps,omitempty"`
	// IngressMbps is the token-bucket policing cap on ingress (0 = unlimited).
	IngressMbps *uint32 `json:"ingressMbps,omitempty"`
}

// CompiledQoSApplyConfiguration constructs a declarative configuration of the CompiledQoS type for use with
// apply.
func CompiledQoS() *CompiledQoSApplyConfiguration {
	return &CompiledQoSApplyConfiguration{}
}

// WithEgressMbps sets the EgressMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EgressMbps field is set to the value of the last call.
func (b *CompiledQoSApplyConfiguration) WithEgressMbps(value uint32) *CompiledQoSApplyConfiguration {
	b.EgressMbps = &value
	return b
}

// WithPublicMbps sets the PublicMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicMbps field is set to the value of the last call.
func (b *CompiledQoSApplyConfiguration) WithPublicMbps(value uint32) *CompiledQoSApplyConfiguration {
	b.PublicMbps = &value
	return b
}

// WithIngressMbps sets the IngressMbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressMbps field is set to the value of the last call.
func (b *CompiledQoSApplyConfiguration) WithIngressMbps(value uint32) *CompiledQoSApplyConfiguration {
	b.IngressMbps = &value
	return b
}
