//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledContainer) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledContainer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledContainerInterface) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledContainerInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledContainerList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledContainerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledContainerSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledContainerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledContainerStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledContainerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledFirewall) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledFirewall"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledFwRule) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledFwRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledLB) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledLB"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledLBPort) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledLBPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledNATSource) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledNATSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledNIC) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledNIC"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledNICList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledNICList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledNICSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledNICSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledNICStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledNICStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledPeerImport) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledPeerImport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVM) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVM"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVMInterface) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVMInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVMList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVMList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVMSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVMSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVMStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVMStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVolumeAttachment) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVolumeAttachment"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVolumeAttachmentList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVolumeAttachmentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVolumeAttachmentSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVolumeAttachmentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledVolumeAttachmentStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.CompiledVolumeAttachmentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Container) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.Container"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.ContainerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.ContainerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.ContainerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoS) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.EgressQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicy) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyRule) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicySpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIP) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InterfaceQoS) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.InterfaceQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancer) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerPort) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalObjectReference) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LocalObjectReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATAllocation) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATAllocation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGateway) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGateway"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewayList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewaySpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewaySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewayStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterface) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PortStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.PortStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RateLimit) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.RateLimit"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VMAntiAffinity) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VMAntiAffinity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VMPlacement) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VMPlacement"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPC) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPC"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeering) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeering"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCReference) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachine) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VirtualMachine"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VirtualMachineList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VirtualMachineSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VirtualMachineStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Volume) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.Volume"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VolumeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VolumeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VolumeStatus"
}
