//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoS) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.EgressQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicy) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyRule) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicySpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirewallPolicyStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FirewallPolicyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIP) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FloatingIPStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.FloatingIPStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InterfaceQoS) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.InterfaceQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancer) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerPort) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LoadBalancerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalObjectReference) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.LocalObjectReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATAllocation) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATAllocation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGateway) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGateway"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewayList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewaySpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewaySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NATGatewayStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterface) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.NetworkInterfaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PortStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.PortStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RateLimit) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.RateLimit"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPC) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPC"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeering) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeering"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringList) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCPeeringStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCPeeringStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCReference) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCSpec) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VPCStatus) OpenAPIModelName() string {
	return "dev.ectobase.net.v1alpha1.VPCStatus"
}
