//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPool) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolList) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolSpec) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterPoolStatus) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.ClusterPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledWorkload) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.CompiledWorkload"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledWorkloadList) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.CompiledWorkloadList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledWorkloadSpec) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.CompiledWorkloadSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompiledWorkloadStatus) OpenAPIModelName() string {
	return "dev.ectobase.platform.v1alpha1.CompiledWorkloadStatus"
}
