//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	platform "github.com/trevex/ectobase/central/apis/platform"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterPool)(nil), (*platform.ClusterPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPool_To_platform_ClusterPool(a.(*ClusterPool), b.(*platform.ClusterPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPool)(nil), (*ClusterPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPool_To_v1alpha1_ClusterPool(a.(*platform.ClusterPool), b.(*ClusterPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolLease)(nil), (*platform.ClusterPoolLease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(a.(*ClusterPoolLease), b.(*platform.ClusterPoolLease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolLease)(nil), (*ClusterPoolLease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(a.(*platform.ClusterPoolLease), b.(*ClusterPoolLease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolList)(nil), (*platform.ClusterPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(a.(*ClusterPoolList), b.(*platform.ClusterPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolList)(nil), (*ClusterPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(a.(*platform.ClusterPoolList), b.(*ClusterPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolSpec)(nil), (*platform.ClusterPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(a.(*ClusterPoolSpec), b.(*platform.ClusterPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolSpec)(nil), (*ClusterPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(a.(*platform.ClusterPoolSpec), b.(*ClusterPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPoolStatus)(nil), (*platform.ClusterPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(a.(*ClusterPoolStatus), b.(*platform.ClusterPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.ClusterPoolStatus)(nil), (*ClusterPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(a.(*platform.ClusterPoolStatus), b.(*ClusterPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CompiledWorkload)(nil), (*platform.CompiledWorkload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CompiledWorkload_To_platform_CompiledWorkload(a.(*CompiledWorkload), b.(*platform.CompiledWorkload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.CompiledWorkload)(nil), (*CompiledWorkload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_CompiledWorkload_To_v1alpha1_CompiledWorkload(a.(*platform.CompiledWorkload), b.(*CompiledWorkload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CompiledWorkloadList)(nil), (*platform.CompiledWorkloadList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CompiledWorkloadList_To_platform_CompiledWorkloadList(a.(*CompiledWorkloadList), b.(*platform.CompiledWorkloadList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.CompiledWorkloadList)(nil), (*CompiledWorkloadList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_CompiledWorkloadList_To_v1alpha1_CompiledWorkloadList(a.(*platform.CompiledWorkloadList), b.(*CompiledWorkloadList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CompiledWorkloadSpec)(nil), (*platform.CompiledWorkloadSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec(a.(*CompiledWorkloadSpec), b.(*platform.CompiledWorkloadSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.CompiledWorkloadSpec)(nil), (*CompiledWorkloadSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec(a.(*platform.CompiledWorkloadSpec), b.(*CompiledWorkloadSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CompiledWorkloadStatus)(nil), (*platform.CompiledWorkloadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus(a.(*CompiledWorkloadStatus), b.(*platform.CompiledWorkloadStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*platform.CompiledWorkloadStatus)(nil), (*CompiledWorkloadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus(a.(*platform.CompiledWorkloadStatus), b.(*CompiledWorkloadStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterPool_To_platform_ClusterPool(in *ClusterPool, out *platform.ClusterPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterPool_To_platform_ClusterPool is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPool_To_platform_ClusterPool(in *ClusterPool, out *platform.ClusterPool, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPool_To_platform_ClusterPool(in, out, s)
}

func autoConvert_platform_ClusterPool_To_v1alpha1_ClusterPool(in *platform.ClusterPool, out *ClusterPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_platform_ClusterPool_To_v1alpha1_ClusterPool is an autogenerated conversion function.
func Convert_platform_ClusterPool_To_v1alpha1_ClusterPool(in *platform.ClusterPool, out *ClusterPool, s conversion.Scope) error {
	return autoConvert_platform_ClusterPool_To_v1alpha1_ClusterPool(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in *ClusterPoolLease, out *platform.ClusterPoolLease, s conversion.Scope) error {
	out.HolderIdentity = in.HolderIdentity
	out.RenewTime = (*v1.MicroTime)(unsafe.Pointer(in.RenewTime))
	return nil
}

// Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in *ClusterPoolLease, out *platform.ClusterPoolLease, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolLease_To_platform_ClusterPoolLease(in, out, s)
}

func autoConvert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in *platform.ClusterPoolLease, out *ClusterPoolLease, s conversion.Scope) error {
	out.HolderIdentity = in.HolderIdentity
	out.RenewTime = (*v1.MicroTime)(unsafe.Pointer(in.RenewTime))
	return nil
}

// Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease is an autogenerated conversion function.
func Convert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in *platform.ClusterPoolLease, out *ClusterPoolLease, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolLease_To_v1alpha1_ClusterPoolLease(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in *ClusterPoolList, out *platform.ClusterPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]platform.ClusterPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in *ClusterPoolList, out *platform.ClusterPoolList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolList_To_platform_ClusterPoolList(in, out, s)
}

func autoConvert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in *platform.ClusterPoolList, out *ClusterPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList is an autogenerated conversion function.
func Convert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in *platform.ClusterPoolList, out *ClusterPoolList, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolList_To_v1alpha1_ClusterPoolList(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in *ClusterPoolSpec, out *platform.ClusterPoolSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.Endpoint = in.Endpoint
	return nil
}

// Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in *ClusterPoolSpec, out *platform.ClusterPoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolSpec_To_platform_ClusterPoolSpec(in, out, s)
}

func autoConvert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in *platform.ClusterPoolSpec, out *ClusterPoolSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.Endpoint = in.Endpoint
	return nil
}

// Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec is an autogenerated conversion function.
func Convert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in *platform.ClusterPoolSpec, out *ClusterPoolSpec, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolSpec_To_v1alpha1_ClusterPoolSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in *ClusterPoolStatus, out *platform.ClusterPoolStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.Allocatable = *(*corev1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Lease = (*platform.ClusterPoolLease)(unsafe.Pointer(in.Lease))
	return nil
}

// Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in *ClusterPoolStatus, out *platform.ClusterPoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPoolStatus_To_platform_ClusterPoolStatus(in, out, s)
}

func autoConvert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in *platform.ClusterPoolStatus, out *ClusterPoolStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.Allocatable = *(*corev1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Lease = (*ClusterPoolLease)(unsafe.Pointer(in.Lease))
	return nil
}

// Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus is an autogenerated conversion function.
func Convert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in *platform.ClusterPoolStatus, out *ClusterPoolStatus, s conversion.Scope) error {
	return autoConvert_platform_ClusterPoolStatus_To_v1alpha1_ClusterPoolStatus(in, out, s)
}

func autoConvert_v1alpha1_CompiledWorkload_To_platform_CompiledWorkload(in *CompiledWorkload, out *platform.CompiledWorkload, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CompiledWorkload_To_platform_CompiledWorkload is an autogenerated conversion function.
func Convert_v1alpha1_CompiledWorkload_To_platform_CompiledWorkload(in *CompiledWorkload, out *platform.CompiledWorkload, s conversion.Scope) error {
	return autoConvert_v1alpha1_CompiledWorkload_To_platform_CompiledWorkload(in, out, s)
}

func autoConvert_platform_CompiledWorkload_To_v1alpha1_CompiledWorkload(in *platform.CompiledWorkload, out *CompiledWorkload, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_platform_CompiledWorkload_To_v1alpha1_CompiledWorkload is an autogenerated conversion function.
func Convert_platform_CompiledWorkload_To_v1alpha1_CompiledWorkload(in *platform.CompiledWorkload, out *CompiledWorkload, s conversion.Scope) error {
	return autoConvert_platform_CompiledWorkload_To_v1alpha1_CompiledWorkload(in, out, s)
}

func autoConvert_v1alpha1_CompiledWorkloadList_To_platform_CompiledWorkloadList(in *CompiledWorkloadList, out *platform.CompiledWorkloadList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]platform.CompiledWorkload)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CompiledWorkloadList_To_platform_CompiledWorkloadList is an autogenerated conversion function.
func Convert_v1alpha1_CompiledWorkloadList_To_platform_CompiledWorkloadList(in *CompiledWorkloadList, out *platform.CompiledWorkloadList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CompiledWorkloadList_To_platform_CompiledWorkloadList(in, out, s)
}

func autoConvert_platform_CompiledWorkloadList_To_v1alpha1_CompiledWorkloadList(in *platform.CompiledWorkloadList, out *CompiledWorkloadList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CompiledWorkload)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_platform_CompiledWorkloadList_To_v1alpha1_CompiledWorkloadList is an autogenerated conversion function.
func Convert_platform_CompiledWorkloadList_To_v1alpha1_CompiledWorkloadList(in *platform.CompiledWorkloadList, out *CompiledWorkloadList, s conversion.Scope) error {
	return autoConvert_platform_CompiledWorkloadList_To_v1alpha1_CompiledWorkloadList(in, out, s)
}

func autoConvert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec(in *CompiledWorkloadSpec, out *platform.CompiledWorkloadSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.Payload = in.Payload
	return nil
}

// Convert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec is an autogenerated conversion function.
func Convert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec(in *CompiledWorkloadSpec, out *platform.CompiledWorkloadSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CompiledWorkloadSpec_To_platform_CompiledWorkloadSpec(in, out, s)
}

func autoConvert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec(in *platform.CompiledWorkloadSpec, out *CompiledWorkloadSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.Payload = in.Payload
	return nil
}

// Convert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec is an autogenerated conversion function.
func Convert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec(in *platform.CompiledWorkloadSpec, out *CompiledWorkloadSpec, s conversion.Scope) error {
	return autoConvert_platform_CompiledWorkloadSpec_To_v1alpha1_CompiledWorkloadSpec(in, out, s)
}

func autoConvert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus(in *CompiledWorkloadStatus, out *platform.CompiledWorkloadStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus is an autogenerated conversion function.
func Convert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus(in *CompiledWorkloadStatus, out *platform.CompiledWorkloadStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CompiledWorkloadStatus_To_platform_CompiledWorkloadStatus(in, out, s)
}

func autoConvert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus(in *platform.CompiledWorkloadStatus, out *CompiledWorkloadStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus is an autogenerated conversion function.
func Convert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus(in *platform.CompiledWorkloadStatus, out *CompiledWorkloadStatus, s conversion.Scope) error {
	return autoConvert_platform_CompiledWorkloadStatus_To_v1alpha1_CompiledWorkloadStatus(in, out, s)
}
