// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// DiskIdentityApplyConfiguration represents a declarative configuration of the DiskIdentity type for use
// with apply.
//
// DiskIdentity is the CSI identity of the disk actually provisioned for this Volume, as observed by
// the pool that provisioned it. It is what makes the disk's lifetime belong to the Volume — which is
// cluster-agnostic — rather than to the placement-scoped attachment that happens to reference it.
//
// The entire CSI source is kept verbatim rather than a handle plus reconstructed parameters:
// rebuilding a ceph-csi PV from StorageClass parameters means re-deriving clusterID, pool, imageName,
// journalPool and up to five distinct secret references by hand, and dropping any one of them yields
// a PV that binds and then fails to mount at NodeStage.
//
// Deliberately a separate declaration from compiled.DiskIdentity, mirroring the
// compute.VMPlacement / compiled.VMPlacement split: the compiled group is self-contained so a pool
// never needs the source API, and an import either way would break that.
type DiskIdentityApplyConfiguration struct {
	// CSI is the provisioned PersistentVolume's CSI source, copied as-is.
	CSI *v1.CSIPersistentVolumeSource `json:"csi,omitempty"`
	// Capacity is the PV's actual capacity, which a driver may round up from the requested Size.
	Capacity *resource.Quantity `json:"capacity,omitempty"`
}

// DiskIdentityApplyConfiguration constructs a declarative configuration of the DiskIdentity type for use with
// apply.
func DiskIdentity() *DiskIdentityApplyConfiguration {
	return &DiskIdentityApplyConfiguration{}
}

// WithCSI sets the CSI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CSI field is set to the value of the last call.
func (b *DiskIdentityApplyConfiguration) WithCSI(value v1.CSIPersistentVolumeSource) *DiskIdentityApplyConfiguration {
	b.CSI = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *DiskIdentityApplyConfiguration) WithCapacity(value resource.Quantity) *DiskIdentityApplyConfiguration {
	b.Capacity = &value
	return b
}
