// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// VolumeSpecApplyConfiguration represents a declarative configuration of the VolumeSpec type for use
// with apply.
//
// VolumeSpec defines a persistent RBD-backed disk for a VM.
type VolumeSpecApplyConfiguration struct {
	// Size is the requested disk size (e.g. 10Gi).
	Size *resource.Quantity `json:"size,omitempty"`
	// StorageClass is the ceph-csi RBD StorageClass; empty uses the cluster default.
	StorageClass *string `json:"storageClass,omitempty"`
	// BootImage, if set, is a containerDisk/registry image imported into the disk
	// (making it bootable). Empty leaves a blank data disk of Size.
	BootImage *string `json:"bootImage,omitempty"`
}

// VolumeSpecApplyConfiguration constructs a declarative configuration of the VolumeSpec type for use with
// apply.
func VolumeSpec() *VolumeSpecApplyConfiguration {
	return &VolumeSpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithSize(value resource.Quantity) *VolumeSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithStorageClass(value string) *VolumeSpecApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithBootImage sets the BootImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootImage field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithBootImage(value string) *VolumeSpecApplyConfiguration {
	b.BootImage = &value
	return b
}
