{{- if .Values.tier1Failover.enabled }}
apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationTemplate
metadata:
  name: ectobase-tier1
  namespace: {{ .Values.tier1Failover.snrNamespace }}
  labels:
    app.kubernetes.io/part-of: ectobase
spec:
  template:
    spec:
      remediationStrategy: {{ .Values.tier1Failover.remediationStrategy }}
{{- if .Values.tier1Failover.watchdog.enabled }}
---
apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationConfig
metadata:
  name: self-node-remediation-config
  namespace: {{ .Values.tier1Failover.snrNamespace }}
  labels:
    app.kubernetes.io/part-of: ectobase
spec:
  watchdogFilePath: {{ .Values.tier1Failover.watchdog.device }}
{{- end }}
{{- end }}
