// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/central/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CompiledVolumeAttachmentsGetter has a method to return a CompiledVolumeAttachmentInterface.
// A group's client should implement this interface.
type CompiledVolumeAttachmentsGetter interface {
	CompiledVolumeAttachments(namespace string) CompiledVolumeAttachmentInterface
}

// CompiledVolumeAttachmentInterface has methods to work with CompiledVolumeAttachment resources.
type CompiledVolumeAttachmentInterface interface {
	Create(ctx context.Context, compiledVolumeAttachment *netv1alpha1.CompiledVolumeAttachment, opts v1.CreateOptions) (*netv1alpha1.CompiledVolumeAttachment, error)
	Update(ctx context.Context, compiledVolumeAttachment *netv1alpha1.CompiledVolumeAttachment, opts v1.UpdateOptions) (*netv1alpha1.CompiledVolumeAttachment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compiledVolumeAttachment *netv1alpha1.CompiledVolumeAttachment, opts v1.UpdateOptions) (*netv1alpha1.CompiledVolumeAttachment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.CompiledVolumeAttachment, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.CompiledVolumeAttachmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.CompiledVolumeAttachment, err error)
	Apply(ctx context.Context, compiledVolumeAttachment *applyconfigurationsnetv1alpha1.CompiledVolumeAttachmentApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.CompiledVolumeAttachment, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, compiledVolumeAttachment *applyconfigurationsnetv1alpha1.CompiledVolumeAttachmentApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.CompiledVolumeAttachment, err error)
	CompiledVolumeAttachmentExpansion
}

// compiledVolumeAttachments implements CompiledVolumeAttachmentInterface
type compiledVolumeAttachments struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.CompiledVolumeAttachment, *netv1alpha1.CompiledVolumeAttachmentList, *applyconfigurationsnetv1alpha1.CompiledVolumeAttachmentApplyConfiguration]
}

// newCompiledVolumeAttachments returns a CompiledVolumeAttachments
func newCompiledVolumeAttachments(c *NetV1alpha1Client, namespace string) *compiledVolumeAttachments {
	return &compiledVolumeAttachments{
		gentype.NewClientWithListAndApply[*netv1alpha1.CompiledVolumeAttachment, *netv1alpha1.CompiledVolumeAttachmentList, *applyconfigurationsnetv1alpha1.CompiledVolumeAttachmentApplyConfiguration](
			"compiledvolumeattachments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.CompiledVolumeAttachment { return &netv1alpha1.CompiledVolumeAttachment{} },
			func() *netv1alpha1.CompiledVolumeAttachmentList { return &netv1alpha1.CompiledVolumeAttachmentList{} },
		),
	}
}
