// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	platformv1alpha1 "github.com/trevex/ectobase/api/platform/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterPoolLister helps list ClusterPools.
// All objects returned here must be treated as read-only.
type ClusterPoolLister interface {
	// List lists all ClusterPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*platformv1alpha1.ClusterPool, err error)
	// Get retrieves the ClusterPool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*platformv1alpha1.ClusterPool, error)
	ClusterPoolListerExpansion
}

// clusterPoolLister implements the ClusterPoolLister interface.
type clusterPoolLister struct {
	listers.ResourceIndexer[*platformv1alpha1.ClusterPool]
}

// NewClusterPoolLister returns a new ClusterPoolLister.
func NewClusterPoolLister(indexer cache.Indexer) ClusterPoolLister {
	return &clusterPoolLister{listers.New[*platformv1alpha1.ClusterPool](indexer, platformv1alpha1.Resource("clusterpool"))}
}
