---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowplane-cni
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - compiled.ectobase.dev
  resources:
  - compilednics
  verbs:
  - get
