// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/trevex/ectobase/central/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CompiledContainers returns a CompiledContainerInformer.
	CompiledContainers() CompiledContainerInformer
	// CompiledNICs returns a CompiledNICInformer.
	CompiledNICs() CompiledNICInformer
	// CompiledVMs returns a CompiledVMInformer.
	CompiledVMs() CompiledVMInformer
	// CompiledVolumeAttachments returns a CompiledVolumeAttachmentInformer.
	CompiledVolumeAttachments() CompiledVolumeAttachmentInformer
	// Containers returns a ContainerInformer.
	Containers() ContainerInformer
	// FirewallPolicies returns a FirewallPolicyInformer.
	FirewallPolicies() FirewallPolicyInformer
	// FloatingIPs returns a FloatingIPInformer.
	FloatingIPs() FloatingIPInformer
	// LoadBalancers returns a LoadBalancerInformer.
	LoadBalancers() LoadBalancerInformer
	// NATGateways returns a NATGatewayInformer.
	NATGateways() NATGatewayInformer
	// NetworkInterfaces returns a NetworkInterfaceInformer.
	NetworkInterfaces() NetworkInterfaceInformer
	// VPCs returns a VPCInformer.
	VPCs() VPCInformer
	// VPCPeerings returns a VPCPeeringInformer.
	VPCPeerings() VPCPeeringInformer
	// VirtualMachines returns a VirtualMachineInformer.
	VirtualMachines() VirtualMachineInformer
	// Volumes returns a VolumeInformer.
	Volumes() VolumeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CompiledContainers returns a CompiledContainerInformer.
func (v *version) CompiledContainers() CompiledContainerInformer {
	return &compiledContainerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledNICs returns a CompiledNICInformer.
func (v *version) CompiledNICs() CompiledNICInformer {
	return &compiledNICInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledVMs returns a CompiledVMInformer.
func (v *version) CompiledVMs() CompiledVMInformer {
	return &compiledVMInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledVolumeAttachments returns a CompiledVolumeAttachmentInformer.
func (v *version) CompiledVolumeAttachments() CompiledVolumeAttachmentInformer {
	return &compiledVolumeAttachmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Containers returns a ContainerInformer.
func (v *version) Containers() ContainerInformer {
	return &containerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FirewallPolicies returns a FirewallPolicyInformer.
func (v *version) FirewallPolicies() FirewallPolicyInformer {
	return &firewallPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FloatingIPs returns a FloatingIPInformer.
func (v *version) FloatingIPs() FloatingIPInformer {
	return &floatingIPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoadBalancers returns a LoadBalancerInformer.
func (v *version) LoadBalancers() LoadBalancerInformer {
	return &loadBalancerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NATGateways returns a NATGatewayInformer.
func (v *version) NATGateways() NATGatewayInformer {
	return &nATGatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkInterfaces returns a NetworkInterfaceInformer.
func (v *version) NetworkInterfaces() NetworkInterfaceInformer {
	return &networkInterfaceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VPCs returns a VPCInformer.
func (v *version) VPCs() VPCInformer {
	return &vPCInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VPCPeerings returns a VPCPeeringInformer.
func (v *version) VPCPeerings() VPCPeeringInformer {
	return &vPCPeeringInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VirtualMachines returns a VirtualMachineInformer.
func (v *version) VirtualMachines() VirtualMachineInformer {
	return &virtualMachineInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Volumes returns a VolumeInformer.
func (v *version) Volumes() VolumeInformer {
	return &volumeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
