{{- if .Values.tier1Failover.enabled }}
apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: ectobase-tier1
  labels:
    app.kubernetes.io/part-of: ectobase
spec:
  minHealthy: {{ .Values.tier1Failover.minHealthy | quote }}
  selector:
{{ toYaml .Values.tier1Failover.nodeSelector | indent 4 }}
  unhealthyConditions:
    - type: Ready
      status: "False"
      duration: {{ .Values.tier1Failover.unhealthyThreshold }}
    - type: Ready
      status: Unknown
      duration: {{ .Values.tier1Failover.unhealthyThreshold }}
  remediationTemplate:
    apiVersion: self-node-remediation.medik8s.io/v1alpha1
    kind: SelfNodeRemediationTemplate
    name: ectobase-tier1
    namespace: {{ .Values.tier1Failover.snrNamespace }}
{{- end }}
