// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/platform/v1alpha1"
	platformv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/platform/v1alpha1"
	typedplatformv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/platform/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRouteBusIdentities implements RouteBusIdentityInterface
type fakeRouteBusIdentities struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.RouteBusIdentity, *v1alpha1.RouteBusIdentityList, *platformv1alpha1.RouteBusIdentityApplyConfiguration]
	Fake *FakePlatformV1alpha1
}

func newFakeRouteBusIdentities(fake *FakePlatformV1alpha1) typedplatformv1alpha1.RouteBusIdentityInterface {
	return &fakeRouteBusIdentities{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.RouteBusIdentity, *v1alpha1.RouteBusIdentityList, *platformv1alpha1.RouteBusIdentityApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("routebusidentities"),
			v1alpha1.SchemeGroupVersion.WithKind("RouteBusIdentity"),
			func() *v1alpha1.RouteBusIdentity { return &v1alpha1.RouteBusIdentity{} },
			func() *v1alpha1.RouteBusIdentityList { return &v1alpha1.RouteBusIdentityList{} },
			func(dst, src *v1alpha1.RouteBusIdentityList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RouteBusIdentityList) []*v1alpha1.RouteBusIdentity {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RouteBusIdentityList, items []*v1alpha1.RouteBusIdentity) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
