// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/platform/v1alpha1"
	platformv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/platform/v1alpha1"
	typedplatformv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/platform/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterPools implements ClusterPoolInterface
type fakeClusterPools struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterPool, *v1alpha1.ClusterPoolList, *platformv1alpha1.ClusterPoolApplyConfiguration]
	Fake *FakePlatformV1alpha1
}

func newFakeClusterPools(fake *FakePlatformV1alpha1) typedplatformv1alpha1.ClusterPoolInterface {
	return &fakeClusterPools{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterPool, *v1alpha1.ClusterPoolList, *platformv1alpha1.ClusterPoolApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterpools"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterPool"),
			func() *v1alpha1.ClusterPool { return &v1alpha1.ClusterPool{} },
			func() *v1alpha1.ClusterPoolList { return &v1alpha1.ClusterPoolList{} },
			func(dst, src *v1alpha1.ClusterPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterPoolList) []*v1alpha1.ClusterPool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterPoolList, items []*v1alpha1.ClusterPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
