// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/compute/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeComputeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeComputeV1alpha1) Containers(namespace string) v1alpha1.ContainerInterface {
	return newFakeContainers(c, namespace)
}

func (c *FakeComputeV1alpha1) VirtualMachines(namespace string) v1alpha1.VirtualMachineInterface {
	return newFakeVirtualMachines(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeComputeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
