// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	compiledv1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	applyconfigurationscompiledv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/compiled/v1alpha1"
	scheme "github.com/trevex/ectobase/hub/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CompiledContainersGetter has a method to return a CompiledContainerInterface.
// A group's client should implement this interface.
type CompiledContainersGetter interface {
	CompiledContainers(namespace string) CompiledContainerInterface
}

// CompiledContainerInterface has methods to work with CompiledContainer resources.
type CompiledContainerInterface interface {
	Create(ctx context.Context, compiledContainer *compiledv1alpha1.CompiledContainer, opts v1.CreateOptions) (*compiledv1alpha1.CompiledContainer, error)
	Update(ctx context.Context, compiledContainer *compiledv1alpha1.CompiledContainer, opts v1.UpdateOptions) (*compiledv1alpha1.CompiledContainer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compiledContainer *compiledv1alpha1.CompiledContainer, opts v1.UpdateOptions) (*compiledv1alpha1.CompiledContainer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*compiledv1alpha1.CompiledContainer, error)
	List(ctx context.Context, opts v1.ListOptions) (*compiledv1alpha1.CompiledContainerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *compiledv1alpha1.CompiledContainer, err error)
	Apply(ctx context.Context, compiledContainer *applyconfigurationscompiledv1alpha1.CompiledContainerApplyConfiguration, opts v1.ApplyOptions) (result *compiledv1alpha1.CompiledContainer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, compiledContainer *applyconfigurationscompiledv1alpha1.CompiledContainerApplyConfiguration, opts v1.ApplyOptions) (result *compiledv1alpha1.CompiledContainer, err error)
	CompiledContainerExpansion
}

// compiledContainers implements CompiledContainerInterface
type compiledContainers struct {
	*gentype.ClientWithListAndApply[*compiledv1alpha1.CompiledContainer, *compiledv1alpha1.CompiledContainerList, *applyconfigurationscompiledv1alpha1.CompiledContainerApplyConfiguration]
}

// newCompiledContainers returns a CompiledContainers
func newCompiledContainers(c *CompiledV1alpha1Client, namespace string) *compiledContainers {
	return &compiledContainers{
		gentype.NewClientWithListAndApply[*compiledv1alpha1.CompiledContainer, *compiledv1alpha1.CompiledContainerList, *applyconfigurationscompiledv1alpha1.CompiledContainerApplyConfiguration](
			"compiledcontainers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *compiledv1alpha1.CompiledContainer { return &compiledv1alpha1.CompiledContainer{} },
			func() *compiledv1alpha1.CompiledContainerList { return &compiledv1alpha1.CompiledContainerList{} },
		),
	}
}
