// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/hub/client-go/clientset/versioned/typed/compiled/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCompiledV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCompiledV1alpha1) CompiledContainers(namespace string) v1alpha1.CompiledContainerInterface {
	return newFakeCompiledContainers(c, namespace)
}

func (c *FakeCompiledV1alpha1) CompiledNICs(namespace string) v1alpha1.CompiledNICInterface {
	return newFakeCompiledNICs(c, namespace)
}

func (c *FakeCompiledV1alpha1) CompiledVMs(namespace string) v1alpha1.CompiledVMInterface {
	return newFakeCompiledVMs(c, namespace)
}

func (c *FakeCompiledV1alpha1) CompiledVolumeAttachments(namespace string) v1alpha1.CompiledVolumeAttachmentInterface {
	return newFakeCompiledVolumeAttachments(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCompiledV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
