// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	computev1alpha1 "github.com/trevex/ectobase/api/compute/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ContainerLister helps list Containers.
// All objects returned here must be treated as read-only.
type ContainerLister interface {
	// List lists all Containers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*computev1alpha1.Container, err error)
	// Containers returns an object that can list and get Containers.
	Containers(namespace string) ContainerNamespaceLister
	ContainerListerExpansion
}

// containerLister implements the ContainerLister interface.
type containerLister struct {
	listers.ResourceIndexer[*computev1alpha1.Container]
}

// NewContainerLister returns a new ContainerLister.
func NewContainerLister(indexer cache.Indexer) ContainerLister {
	return &containerLister{listers.New[*computev1alpha1.Container](indexer, computev1alpha1.Resource("container"))}
}

// Containers returns an object that can list and get Containers.
func (s *containerLister) Containers(namespace string) ContainerNamespaceLister {
	return containerNamespaceLister{listers.NewNamespaced[*computev1alpha1.Container](s.ResourceIndexer, namespace)}
}

// ContainerNamespaceLister helps list and get Containers.
// All objects returned here must be treated as read-only.
type ContainerNamespaceLister interface {
	// List lists all Containers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*computev1alpha1.Container, err error)
	// Get retrieves the Container from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*computev1alpha1.Container, error)
	ContainerNamespaceListerExpansion
}

// containerNamespaceLister implements the ContainerNamespaceLister
// interface.
type containerNamespaceLister struct {
	listers.ResourceIndexer[*computev1alpha1.Container]
}
