//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Volume) OpenAPIModelName() string {
	return "dev.ectobase.storage.v1alpha1.Volume"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeList) OpenAPIModelName() string {
	return "dev.ectobase.storage.v1alpha1.VolumeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeSpec) OpenAPIModelName() string {
	return "dev.ectobase.storage.v1alpha1.VolumeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeStatus) OpenAPIModelName() string {
	return "dev.ectobase.storage.v1alpha1.VolumeStatus"
}
