// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LBPoolLister helps list LBPools.
// All objects returned here must be treated as read-only.
type LBPoolLister interface {
	// List lists all LBPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netv1alpha1.LBPool, err error)
	// LBPools returns an object that can list and get LBPools.
	LBPools(namespace string) LBPoolNamespaceLister
	LBPoolListerExpansion
}

// lBPoolLister implements the LBPoolLister interface.
type lBPoolLister struct {
	listers.ResourceIndexer[*netv1alpha1.LBPool]
}

// NewLBPoolLister returns a new LBPoolLister.
func NewLBPoolLister(indexer cache.Indexer) LBPoolLister {
	return &lBPoolLister{listers.New[*netv1alpha1.LBPool](indexer, netv1alpha1.Resource("lbpool"))}
}

// LBPools returns an object that can list and get LBPools.
func (s *lBPoolLister) LBPools(namespace string) LBPoolNamespaceLister {
	return lBPoolNamespaceLister{listers.NewNamespaced[*netv1alpha1.LBPool](s.ResourceIndexer, namespace)}
}

// LBPoolNamespaceLister helps list and get LBPools.
// All objects returned here must be treated as read-only.
type LBPoolNamespaceLister interface {
	// List lists all LBPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netv1alpha1.LBPool, err error)
	// Get retrieves the LBPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netv1alpha1.LBPool, error)
	LBPoolNamespaceListerExpansion
}

// lBPoolNamespaceLister implements the LBPoolNamespaceLister
// interface.
type lBPoolNamespaceLister struct {
	listers.ResourceIndexer[*netv1alpha1.LBPool]
}
