// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledPeerImportApplyConfiguration represents a declarative configuration of the CompiledPeerImport type for use
// with apply.
//
// CompiledPeerImport is one peer VPC's reachability import for a NIC.
type CompiledPeerImportApplyConfiguration struct {
	// PeerVNI is the peer VPC's VNI to subscribe to on routebus.
	PeerVNI *int32 `json:"peerVni,omitempty"`
	// ImportPrefixes is the peer's exposedPrefixes: only peer routes within these CIDRs are
	// imported (filter applied importer-side).
	ImportPrefixes []string `json:"importPrefixes,omitempty"`
}

// CompiledPeerImportApplyConfiguration constructs a declarative configuration of the CompiledPeerImport type for use with
// apply.
func CompiledPeerImport() *CompiledPeerImportApplyConfiguration {
	return &CompiledPeerImportApplyConfiguration{}
}

// WithPeerVNI sets the PeerVNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerVNI field is set to the value of the last call.
func (b *CompiledPeerImportApplyConfiguration) WithPeerVNI(value int32) *CompiledPeerImportApplyConfiguration {
	b.PeerVNI = &value
	return b
}

// WithImportPrefixes adds the given value to the ImportPrefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImportPrefixes field.
func (b *CompiledPeerImportApplyConfiguration) WithImportPrefixes(values ...string) *CompiledPeerImportApplyConfiguration {
	for i := range values {
		b.ImportPrefixes = append(b.ImportPrefixes, values[i])
	}
	return b
}
