// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	platformv1alpha1 "github.com/trevex/ectobase/central/apis/platform/v1alpha1"
	applyconfigurationsplatformv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/platform/v1alpha1"
	scheme "github.com/trevex/ectobase/central/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CompiledWorkloadsGetter has a method to return a CompiledWorkloadInterface.
// A group's client should implement this interface.
type CompiledWorkloadsGetter interface {
	CompiledWorkloads() CompiledWorkloadInterface
}

// CompiledWorkloadInterface has methods to work with CompiledWorkload resources.
type CompiledWorkloadInterface interface {
	Create(ctx context.Context, compiledWorkload *platformv1alpha1.CompiledWorkload, opts v1.CreateOptions) (*platformv1alpha1.CompiledWorkload, error)
	Update(ctx context.Context, compiledWorkload *platformv1alpha1.CompiledWorkload, opts v1.UpdateOptions) (*platformv1alpha1.CompiledWorkload, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compiledWorkload *platformv1alpha1.CompiledWorkload, opts v1.UpdateOptions) (*platformv1alpha1.CompiledWorkload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*platformv1alpha1.CompiledWorkload, error)
	List(ctx context.Context, opts v1.ListOptions) (*platformv1alpha1.CompiledWorkloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *platformv1alpha1.CompiledWorkload, err error)
	Apply(ctx context.Context, compiledWorkload *applyconfigurationsplatformv1alpha1.CompiledWorkloadApplyConfiguration, opts v1.ApplyOptions) (result *platformv1alpha1.CompiledWorkload, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, compiledWorkload *applyconfigurationsplatformv1alpha1.CompiledWorkloadApplyConfiguration, opts v1.ApplyOptions) (result *platformv1alpha1.CompiledWorkload, err error)
	CompiledWorkloadExpansion
}

// compiledWorkloads implements CompiledWorkloadInterface
type compiledWorkloads struct {
	*gentype.ClientWithListAndApply[*platformv1alpha1.CompiledWorkload, *platformv1alpha1.CompiledWorkloadList, *applyconfigurationsplatformv1alpha1.CompiledWorkloadApplyConfiguration]
}

// newCompiledWorkloads returns a CompiledWorkloads
func newCompiledWorkloads(c *PlatformV1alpha1Client) *compiledWorkloads {
	return &compiledWorkloads{
		gentype.NewClientWithListAndApply[*platformv1alpha1.CompiledWorkload, *platformv1alpha1.CompiledWorkloadList, *applyconfigurationsplatformv1alpha1.CompiledWorkloadApplyConfiguration](
			"compiledworkloads",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *platformv1alpha1.CompiledWorkload { return &platformv1alpha1.CompiledWorkload{} },
			func() *platformv1alpha1.CompiledWorkloadList { return &platformv1alpha1.CompiledWorkloadList{} },
		),
	}
}
