// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterPoolSpecApplyConfiguration represents a declarative configuration of the ClusterPoolSpec type for use
// with apply.
//
// ClusterPoolSpec defines the desired state of a ClusterPool.
type ClusterPoolSpecApplyConfiguration struct {
	// Region is the region the attached cluster resides in.
	Region *string `json:"region,omitempty"`
	// Endpoint is the reachable API endpoint of the attached cluster.
	Endpoint *string `json:"endpoint,omitempty"`
	// UnderlayPrefix is this cluster's underlay aggregate (a CIDR that contains every node's
	// underlay address, e.g. "fd00:cafe:1a2b::/48"). Declaring it makes Tier-2 fencing COMPLETE by
	// construction: the dispatch fences this one prefix instead of enumerating node /64s, so a node it
	// never observed — one that joined while the pool was unreachable — is fenced too.
	//
	// It is also the pool's route-bus certificate constraint: the dispatch signer IP-name-constrains
	// the pool's intermediate CA to exactly this prefix, so the pool can only mint node leaves whose
	// IP SAN lies inside it, and the reflector only trusts nexthops equal to such a SAN. A pool must
	// declare it to join the route bus: with it empty, the signer denies the pool's intermediate.
	//
	// It must be a CIDR in canonical form (no host bits, no IPv4-mapped IPv6), at least /32 for
	// IPv6 or /16 for IPv4. The signer also denies a prefix that overlaps another ClusterPool's
	// (the pool enrolled later is denied) or a fleet identity's permitted ranges. If a reported node
	// /64 lies outside it, failover treats its coverage as incomplete and blocks the rebind.
	//
	// It is dispatch configuration, set when the pool is registered, deliberately NOT reported by
	// the broker: neither a fence coordinate nor a certificate constraint may be derived from the
	// entity it bounds. A fenced pool is by definition the one you have lost contact with, and a
	// constraint the pool chooses itself constrains nothing.
	//
	// When empty, failover falls back to the broker-reported node /64s, which is only safe while
	// every node in the cluster shares one /64 (each node's identity being a /128 inside it). If
	// the reported set contains MORE than one distinct /64, the cluster spans /64s, an unobserved
	// node could sit in an unreported one. Failover then fences the /64s it knows about but blocks
	// the rebind, because fencing incompletely must not reattach a disk an unfenced node may still
	// write to. Set this field to unblock it. See docs/architecture/failover.md.
	UnderlayPrefix *string `json:"underlayPrefix,omitempty"`
}

// ClusterPoolSpecApplyConfiguration constructs a declarative configuration of the ClusterPoolSpec type for use with
// apply.
func ClusterPoolSpec() *ClusterPoolSpecApplyConfiguration {
	return &ClusterPoolSpecApplyConfiguration{}
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *ClusterPoolSpecApplyConfiguration) WithRegion(value string) *ClusterPoolSpecApplyConfiguration {
	b.Region = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *ClusterPoolSpecApplyConfiguration) WithEndpoint(value string) *ClusterPoolSpecApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithUnderlayPrefix sets the UnderlayPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnderlayPrefix field is set to the value of the last call.
func (b *ClusterPoolSpecApplyConfiguration) WithUnderlayPrefix(value string) *ClusterPoolSpecApplyConfiguration {
	b.UnderlayPrefix = &value
	return b
}
