// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RouteBusIdentityStatusApplyConfiguration represents a declarative configuration of the RouteBusIdentityStatus type for use
// with apply.
//
// RouteBusIdentityStatus carries the signer's response: the signed intermediate and the
// root CA bundle the reflector trusts.
type RouteBusIdentityStatusApplyConfiguration struct {
	// Certificate is the PEM-encoded signed intermediate CA certificate (the CSR response).
	Certificate []byte `json:"certificate,omitempty"`
	// CABundle is the PEM-encoded root CA the reflector trusts, so the pool can present the
	// full chain (leaf -> intermediate -> root).
	CABundle []byte `json:"caBundle,omitempty"`
	// Conditions represent the latest observations (e.g. Signed / Denied).
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RouteBusIdentityStatusApplyConfiguration constructs a declarative configuration of the RouteBusIdentityStatus type for use with
// apply.
func RouteBusIdentityStatus() *RouteBusIdentityStatusApplyConfiguration {
	return &RouteBusIdentityStatusApplyConfiguration{}
}

// WithCertificate adds the given value to the Certificate field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Certificate field.
func (b *RouteBusIdentityStatusApplyConfiguration) WithCertificate(values ...byte) *RouteBusIdentityStatusApplyConfiguration {
	for i := range values {
		b.Certificate = append(b.Certificate, values[i])
	}
	return b
}

// WithCABundle adds the given value to the CABundle field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CABundle field.
func (b *RouteBusIdentityStatusApplyConfiguration) WithCABundle(values ...byte) *RouteBusIdentityStatusApplyConfiguration {
	for i := range values {
		b.CABundle = append(b.CABundle, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RouteBusIdentityStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RouteBusIdentityStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
