// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledContainerStatusApplyConfiguration represents a declarative configuration of the CompiledContainerStatus type for use
// with apply.
//
// CompiledContainerStatus is the observed state of a CompiledContainer.
type CompiledContainerStatusApplyConfiguration struct {
	// State is the materialization state (e.g. Applied, Pending).
	State *string `json:"state,omitempty"`
}

// CompiledContainerStatusApplyConfiguration constructs a declarative configuration of the CompiledContainerStatus type for use with
// apply.
func CompiledContainerStatus() *CompiledContainerStatusApplyConfiguration {
	return &CompiledContainerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CompiledContainerStatusApplyConfiguration) WithState(value string) *CompiledContainerStatusApplyConfiguration {
	b.State = &value
	return b
}
