// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledNICSpecApplyConfiguration represents a declarative configuration of the CompiledNICSpec type for use
// with apply.
//
// CompiledNICSpec is the fully lowered per-NIC STATIC POLICY the control plane hands to a node:
// identity, VNI, overlay IPs, firewall rules (resolved from FirewallPolicy selectors), egress-SNAT
// allocations, LB membership, and peer imports — derived from the NetworkInterface + VPC +
// FirewallPolicy + LoadBalancer + NATGateway + VPCPeering so the agent never reads those directly.
//
// The source NetworkInterface is the CompiledNIC's OWNER (a controller ownerReference) and its name
// is encoded in the object name — so the spec carries no NICRef. It also deliberately does NOT carry
// the NIC's underlay /128: that is node-local state the dataplane allocates at attach, and the agent
// obtains it from the local DataplaneNode (ListInterfaces) to announce overlay routes with the
// correct node-local nexthop. Keeping node-local state out of this central object avoids a
// compile->sync round-trip that would lag (and flap) the announced nexthop.
type CompiledNICSpecApplyConfiguration struct {
	// ClusterName is the cluster this compiled NIC is bound to (the pod->node
	// binding). Set by the compiler from the owning VirtualMachine's placement,
	// or the compiler's --cluster-name default for NICs with no owning VM.
	// The per-cluster broker selects on this field.
	ClusterName *string `json:"clusterName,omitempty"`
	// VNI is the effective VXLAN network identifier for this NIC (resolved from the NIC's
	// status.vni, falling back to its VPC's status.vni).
	VNI *int32 `json:"vni,omitempty"`
	// Port describes the dataplane port allocated for this interface.
	Port *PortStatusApplyConfiguration `json:"port,omitempty"`
	// OverlayIPs are the guest overlay IP addresses.
	OverlayIPs []string `json:"overlayIPs,omitempty"`
	// Firewall holds the compiled ingress and egress firewall rules.
	Firewall *CompiledFirewallApplyConfiguration `json:"firewall,omitempty"`
	// NAT lists the egress-SNAT sources for this NIC's overlay IPs — one entry per NATGateway
	// allocation whose source is one of this NIC's IPs. Empty if the NIC's VPC has no NAT gateway.
	NAT []CompiledNATSourceApplyConfiguration `json:"nat,omitempty"`
	// LB lists the load balancers this NIC is a backend of. Pure forwarding membership —
	// it grants NO firewall permission (that comes solely from FirewallPolicy).
	LB []CompiledLBApplyConfiguration `json:"lb,omitempty"`
	// PeerImports lists peer VPCs whose routes this NIC imports (reachability only — grants NO
	// firewall permission; that comes solely from FirewallPolicy). Populated from Ready VPCPeerings
	// involving this NIC's VPC.
	PeerImports []CompiledPeerImportApplyConfiguration `json:"peerImports,omitempty"`
	// MAC is the guest L2 address copied from the source NetworkInterface. The CNI
	// programs it as the datapath guest MAC (empty for containers — the datapath derives one).
	MAC *string `json:"mac,omitempty"`
}

// CompiledNICSpecApplyConfiguration constructs a declarative configuration of the CompiledNICSpec type for use with
// apply.
func CompiledNICSpec() *CompiledNICSpecApplyConfiguration {
	return &CompiledNICSpecApplyConfiguration{}
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *CompiledNICSpecApplyConfiguration) WithClusterName(value string) *CompiledNICSpecApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *CompiledNICSpecApplyConfiguration) WithVNI(value int32) *CompiledNICSpecApplyConfiguration {
	b.VNI = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *CompiledNICSpecApplyConfiguration) WithPort(value *PortStatusApplyConfiguration) *CompiledNICSpecApplyConfiguration {
	b.Port = value
	return b
}

// WithOverlayIPs adds the given value to the OverlayIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OverlayIPs field.
func (b *CompiledNICSpecApplyConfiguration) WithOverlayIPs(values ...string) *CompiledNICSpecApplyConfiguration {
	for i := range values {
		b.OverlayIPs = append(b.OverlayIPs, values[i])
	}
	return b
}

// WithFirewall sets the Firewall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Firewall field is set to the value of the last call.
func (b *CompiledNICSpecApplyConfiguration) WithFirewall(value *CompiledFirewallApplyConfiguration) *CompiledNICSpecApplyConfiguration {
	b.Firewall = value
	return b
}

// WithNAT adds the given value to the NAT field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NAT field.
func (b *CompiledNICSpecApplyConfiguration) WithNAT(values ...*CompiledNATSourceApplyConfiguration) *CompiledNICSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNAT")
		}
		b.NAT = append(b.NAT, *values[i])
	}
	return b
}

// WithLB adds the given value to the LB field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LB field.
func (b *CompiledNICSpecApplyConfiguration) WithLB(values ...*CompiledLBApplyConfiguration) *CompiledNICSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLB")
		}
		b.LB = append(b.LB, *values[i])
	}
	return b
}

// WithPeerImports adds the given value to the PeerImports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PeerImports field.
func (b *CompiledNICSpecApplyConfiguration) WithPeerImports(values ...*CompiledPeerImportApplyConfiguration) *CompiledNICSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPeerImports")
		}
		b.PeerImports = append(b.PeerImports, *values[i])
	}
	return b
}

// WithMAC sets the MAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MAC field is set to the value of the last call.
func (b *CompiledNICSpecApplyConfiguration) WithMAC(value string) *CompiledNICSpecApplyConfiguration {
	b.MAC = &value
	return b
}
