// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type FirewallPolicyExpansion interface{}

type FloatingIPExpansion interface{}

type LBPoolExpansion interface{}

type LoadBalancerExpansion interface{}

type NATGatewayExpansion interface{}

type NetworkInterfaceExpansion interface{}

type SubnetExpansion interface{}

type VPCExpansion interface{}

type VPCPeeringExpansion interface{}
