// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPAllocationsGetter has a method to return a IPAllocationInterface.
// A group's client should implement this interface.
type IPAllocationsGetter interface {
	IPAllocations(namespace string) IPAllocationInterface
}

// IPAllocationInterface has methods to work with IPAllocation resources.
type IPAllocationInterface interface {
	Create(ctx context.Context, iPAllocation *netv1alpha1.IPAllocation, opts v1.CreateOptions) (*netv1alpha1.IPAllocation, error)
	Update(ctx context.Context, iPAllocation *netv1alpha1.IPAllocation, opts v1.UpdateOptions) (*netv1alpha1.IPAllocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.IPAllocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.IPAllocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.IPAllocation, err error)
	Apply(ctx context.Context, iPAllocation *applyconfigurationsnetv1alpha1.IPAllocationApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.IPAllocation, err error)
	IPAllocationExpansion
}

// iPAllocations implements IPAllocationInterface
type iPAllocations struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.IPAllocation, *netv1alpha1.IPAllocationList, *applyconfigurationsnetv1alpha1.IPAllocationApplyConfiguration]
}

// newIPAllocations returns a IPAllocations
func newIPAllocations(c *NetV1alpha1Client, namespace string) *iPAllocations {
	return &iPAllocations{
		gentype.NewClientWithListAndApply[*netv1alpha1.IPAllocation, *netv1alpha1.IPAllocationList, *applyconfigurationsnetv1alpha1.IPAllocationApplyConfiguration](
			"ipallocations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.IPAllocation { return &netv1alpha1.IPAllocation{} },
			func() *netv1alpha1.IPAllocationList { return &netv1alpha1.IPAllocationList{} },
		),
	}
}
