// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPoolsGetter has a method to return a IPPoolInterface.
// A group's client should implement this interface.
type IPPoolsGetter interface {
	IPPools(namespace string) IPPoolInterface
}

// IPPoolInterface has methods to work with IPPool resources.
type IPPoolInterface interface {
	Create(ctx context.Context, iPPool *netv1alpha1.IPPool, opts v1.CreateOptions) (*netv1alpha1.IPPool, error)
	Update(ctx context.Context, iPPool *netv1alpha1.IPPool, opts v1.UpdateOptions) (*netv1alpha1.IPPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPPool *netv1alpha1.IPPool, opts v1.UpdateOptions) (*netv1alpha1.IPPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.IPPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.IPPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.IPPool, err error)
	Apply(ctx context.Context, iPPool *applyconfigurationsnetv1alpha1.IPPoolApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.IPPool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, iPPool *applyconfigurationsnetv1alpha1.IPPoolApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.IPPool, err error)
	IPPoolExpansion
}

// iPPools implements IPPoolInterface
type iPPools struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.IPPool, *netv1alpha1.IPPoolList, *applyconfigurationsnetv1alpha1.IPPoolApplyConfiguration]
}

// newIPPools returns a IPPools
func newIPPools(c *NetV1alpha1Client, namespace string) *iPPools {
	return &iPPools{
		gentype.NewClientWithListAndApply[*netv1alpha1.IPPool, *netv1alpha1.IPPoolList, *applyconfigurationsnetv1alpha1.IPPoolApplyConfiguration](
			"ippools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.IPPool { return &netv1alpha1.IPPool{} },
			func() *netv1alpha1.IPPoolList { return &netv1alpha1.IPPoolList{} },
		),
	}
}
