// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetsGetter has a method to return a SubnetInterface.
// A group's client should implement this interface.
type SubnetsGetter interface {
	Subnets(namespace string) SubnetInterface
}

// SubnetInterface has methods to work with Subnet resources.
type SubnetInterface interface {
	Create(ctx context.Context, subnet *netv1alpha1.Subnet, opts v1.CreateOptions) (*netv1alpha1.Subnet, error)
	Update(ctx context.Context, subnet *netv1alpha1.Subnet, opts v1.UpdateOptions) (*netv1alpha1.Subnet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnet *netv1alpha1.Subnet, opts v1.UpdateOptions) (*netv1alpha1.Subnet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.Subnet, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.SubnetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.Subnet, err error)
	Apply(ctx context.Context, subnet *applyconfigurationsnetv1alpha1.SubnetApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.Subnet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, subnet *applyconfigurationsnetv1alpha1.SubnetApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.Subnet, err error)
	SubnetExpansion
}

// subnets implements SubnetInterface
type subnets struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.Subnet, *netv1alpha1.SubnetList, *applyconfigurationsnetv1alpha1.SubnetApplyConfiguration]
}

// newSubnets returns a Subnets
func newSubnets(c *NetV1alpha1Client, namespace string) *subnets {
	return &subnets{
		gentype.NewClientWithListAndApply[*netv1alpha1.Subnet, *netv1alpha1.SubnetList, *applyconfigurationsnetv1alpha1.SubnetApplyConfiguration](
			"subnets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.Subnet { return &netv1alpha1.Subnet{} },
			func() *netv1alpha1.SubnetList { return &netv1alpha1.SubnetList{} },
		),
	}
}
