// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBPoolStatusApplyConfiguration represents a declarative configuration of the LBPoolStatus type for use
// with apply.
//
// LBPoolStatus is the observed state of an LBPool.
type LBPoolStatusApplyConfiguration struct {
	// State is the current lifecycle state (e.g. Pending, Ready).
	State *string `json:"state,omitempty"`
	// Used is the number of allocated VIP addresses.
	Used *int32 `json:"used,omitempty"`
	// Total is the total number of allocatable VIP addresses.
	Total *int32 `json:"total,omitempty"`
}

// LBPoolStatusApplyConfiguration constructs a declarative configuration of the LBPoolStatus type for use with
// apply.
func LBPoolStatus() *LBPoolStatusApplyConfiguration {
	return &LBPoolStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LBPoolStatusApplyConfiguration) WithState(value string) *LBPoolStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithUsed sets the Used field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Used field is set to the value of the last call.
func (b *LBPoolStatusApplyConfiguration) WithUsed(value int32) *LBPoolStatusApplyConfiguration {
	b.Used = &value
	return b
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *LBPoolStatusApplyConfiguration) WithTotal(value int32) *LBPoolStatusApplyConfiguration {
	b.Total = &value
	return b
}
