// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerStatusApplyConfiguration represents a declarative configuration of the LoadBalancerStatus type for use
// with apply.
//
// LoadBalancerStatus is the observed state of a LoadBalancer.
type LoadBalancerStatusApplyConfiguration struct {
	// State is the lifecycle state (Pending | Ready).
	State *string `json:"state,omitempty"`
	// AllocatedIP is the authoritative address assigned by the LB address allocator. Mirrors
	// NetworkInterface.status.allocatedIPs: spec is the request, status is the truth.
	AllocatedIP *string `json:"allocatedIP,omitempty"`
	// ObservedGeneration is the Spec generation the allocation reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// LoadBalancerStatusApplyConfiguration constructs a declarative configuration of the LoadBalancerStatus type for use with
// apply.
func LoadBalancerStatus() *LoadBalancerStatusApplyConfiguration {
	return &LoadBalancerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithState(value string) *LoadBalancerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithAllocatedIP sets the AllocatedIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocatedIP field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithAllocatedIP(value string) *LoadBalancerStatusApplyConfiguration {
	b.AllocatedIP = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithObservedGeneration(value int64) *LoadBalancerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
