// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerStatusApplyConfiguration represents a declarative configuration of the LoadBalancerStatus type for use
// with apply.
//
// LoadBalancerStatus is the observed state of a LoadBalancer.
type LoadBalancerStatusApplyConfiguration struct {
	// State is the lifecycle state (Pending | Ready).
	State *string `json:"state,omitempty"`
}

// LoadBalancerStatusApplyConfiguration constructs a declarative configuration of the LoadBalancerStatus type for use with
// apply.
func LoadBalancerStatus() *LoadBalancerStatusApplyConfiguration {
	return &LoadBalancerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithState(value string) *LoadBalancerStatusApplyConfiguration {
	b.State = &value
	return b
}
