// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubnetSpecApplyConfiguration represents a declarative configuration of the SubnetSpec type for use
// with apply.
//
// SubnetSpec is the desired state of a Subnet (a VPC-scoped v4/v6 prefix range).
type SubnetSpecApplyConfiguration struct {
	// VPCRef references the owning VPC within the same namespace.
	VPCRef *LocalObjectReferenceApplyConfiguration `json:"vpcRef,omitempty"`
	// V4Prefix optionally pins the IPv4 CIDR for this subnet.
	V4Prefix *string `json:"v4Prefix,omitempty"`
	// V6Prefix optionally pins the IPv6 CIDR for this subnet.
	V6Prefix *string `json:"v6Prefix,omitempty"`
	// ReservedIPs are addresses held back from allocation within this subnet.
	ReservedIPs []string `json:"reservedIPs,omitempty"`
}

// SubnetSpecApplyConfiguration constructs a declarative configuration of the SubnetSpec type for use with
// apply.
func SubnetSpec() *SubnetSpecApplyConfiguration {
	return &SubnetSpecApplyConfiguration{}
}

// WithVPCRef sets the VPCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPCRef field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithVPCRef(value *LocalObjectReferenceApplyConfiguration) *SubnetSpecApplyConfiguration {
	b.VPCRef = value
	return b
}

// WithV4Prefix sets the V4Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V4Prefix field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithV4Prefix(value string) *SubnetSpecApplyConfiguration {
	b.V4Prefix = &value
	return b
}

// WithV6Prefix sets the V6Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V6Prefix field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithV6Prefix(value string) *SubnetSpecApplyConfiguration {
	b.V6Prefix = &value
	return b
}

// WithReservedIPs adds the given value to the ReservedIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReservedIPs field.
func (b *SubnetSpecApplyConfiguration) WithReservedIPs(values ...string) *SubnetSpecApplyConfiguration {
	for i := range values {
		b.ReservedIPs = append(b.ReservedIPs, values[i])
	}
	return b
}
