// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VPCSpecApplyConfiguration represents a declarative configuration of the VPCSpec type for use
// with apply.
//
// VPCSpec is the desired state of a VPC (an isolation domain / overlay network).
type VPCSpecApplyConfiguration struct {
	// VNI optionally pins the VXLAN network identifier. When nil or 0, the VNI is
	// allocated by the central cluster from the global VNI space.
	VNI *int32 `json:"vni,omitempty"`
	// DefaultPolicy sets what happens to traffic no firewall rule matches. Allow: it passes (rules
	// carve out denies). Deny: it drops, in every direction (rules carve out allows). Unset keeps
	// Kubernetes NetworkPolicy semantics per direction: a direction no policy governs is open, a
	// governed direction admits only what its rules allow. The VPC's FirewallDefault condition
	// reports the posture in effect.
	DefaultPolicy *string `json:"defaultPolicy,omitempty"`
}

// VPCSpecApplyConfiguration constructs a declarative configuration of the VPCSpec type for use with
// apply.
func VPCSpec() *VPCSpecApplyConfiguration {
	return &VPCSpecApplyConfiguration{}
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *VPCSpecApplyConfiguration) WithVNI(value int32) *VPCSpecApplyConfiguration {
	b.VNI = &value
	return b
}

// WithDefaultPolicy sets the DefaultPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultPolicy field is set to the value of the last call.
func (b *VPCSpecApplyConfiguration) WithDefaultPolicy(value string) *VPCSpecApplyConfiguration {
	b.DefaultPolicy = &value
	return b
}
