// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ContainerListerExpansion allows custom methods to be added to
// ContainerLister.
type ContainerListerExpansion interface{}

// ContainerNamespaceListerExpansion allows custom methods to be added to
// ContainerNamespaceLister.
type ContainerNamespaceListerExpansion interface{}

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}
