// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/hub/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FloatingIPsGetter has a method to return a FloatingIPInterface.
// A group's client should implement this interface.
type FloatingIPsGetter interface {
	FloatingIPs(namespace string) FloatingIPInterface
}

// FloatingIPInterface has methods to work with FloatingIP resources.
type FloatingIPInterface interface {
	Create(ctx context.Context, floatingIP *netv1alpha1.FloatingIP, opts v1.CreateOptions) (*netv1alpha1.FloatingIP, error)
	Update(ctx context.Context, floatingIP *netv1alpha1.FloatingIP, opts v1.UpdateOptions) (*netv1alpha1.FloatingIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, floatingIP *netv1alpha1.FloatingIP, opts v1.UpdateOptions) (*netv1alpha1.FloatingIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.FloatingIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.FloatingIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.FloatingIP, err error)
	Apply(ctx context.Context, floatingIP *applyconfigurationsnetv1alpha1.FloatingIPApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.FloatingIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, floatingIP *applyconfigurationsnetv1alpha1.FloatingIPApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.FloatingIP, err error)
	FloatingIPExpansion
}

// floatingIPs implements FloatingIPInterface
type floatingIPs struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.FloatingIP, *netv1alpha1.FloatingIPList, *applyconfigurationsnetv1alpha1.FloatingIPApplyConfiguration]
}

// newFloatingIPs returns a FloatingIPs
func newFloatingIPs(c *NetV1alpha1Client, namespace string) *floatingIPs {
	return &floatingIPs{
		gentype.NewClientWithListAndApply[*netv1alpha1.FloatingIP, *netv1alpha1.FloatingIPList, *applyconfigurationsnetv1alpha1.FloatingIPApplyConfiguration](
			"floatingips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.FloatingIP { return &netv1alpha1.FloatingIP{} },
			func() *netv1alpha1.FloatingIPList { return &netv1alpha1.FloatingIPList{} },
		),
	}
}
