// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/hub/client-go/applyconfigurations/net/v1alpha1"
	scheme "github.com/trevex/ectobase/hub/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LoadBalancersGetter has a method to return a LoadBalancerInterface.
// A group's client should implement this interface.
type LoadBalancersGetter interface {
	LoadBalancers(namespace string) LoadBalancerInterface
}

// LoadBalancerInterface has methods to work with LoadBalancer resources.
type LoadBalancerInterface interface {
	Create(ctx context.Context, loadBalancer *netv1alpha1.LoadBalancer, opts v1.CreateOptions) (*netv1alpha1.LoadBalancer, error)
	Update(ctx context.Context, loadBalancer *netv1alpha1.LoadBalancer, opts v1.UpdateOptions) (*netv1alpha1.LoadBalancer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, loadBalancer *netv1alpha1.LoadBalancer, opts v1.UpdateOptions) (*netv1alpha1.LoadBalancer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netv1alpha1.LoadBalancer, error)
	List(ctx context.Context, opts v1.ListOptions) (*netv1alpha1.LoadBalancerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netv1alpha1.LoadBalancer, err error)
	Apply(ctx context.Context, loadBalancer *applyconfigurationsnetv1alpha1.LoadBalancerApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.LoadBalancer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, loadBalancer *applyconfigurationsnetv1alpha1.LoadBalancerApplyConfiguration, opts v1.ApplyOptions) (result *netv1alpha1.LoadBalancer, err error)
	LoadBalancerExpansion
}

// loadBalancers implements LoadBalancerInterface
type loadBalancers struct {
	*gentype.ClientWithListAndApply[*netv1alpha1.LoadBalancer, *netv1alpha1.LoadBalancerList, *applyconfigurationsnetv1alpha1.LoadBalancerApplyConfiguration]
}

// newLoadBalancers returns a LoadBalancers
func newLoadBalancers(c *NetV1alpha1Client, namespace string) *loadBalancers {
	return &loadBalancers{
		gentype.NewClientWithListAndApply[*netv1alpha1.LoadBalancer, *netv1alpha1.LoadBalancerList, *applyconfigurationsnetv1alpha1.LoadBalancerApplyConfiguration](
			"loadbalancers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netv1alpha1.LoadBalancer { return &netv1alpha1.LoadBalancer{} },
			func() *netv1alpha1.LoadBalancerList { return &netv1alpha1.LoadBalancerList{} },
		),
	}
}
