// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterPoolStatusApplyConfiguration represents a declarative configuration of the ClusterPoolStatus type for use
// with apply.
//
// ClusterPoolStatus defines the observed state of a ClusterPool.
type ClusterPoolStatusApplyConfiguration struct {
	// Phase is the current lifecycle phase of the ClusterPool.
	Phase *string `json:"phase,omitempty"`
	// Conditions represent the latest available observations of the ClusterPool's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Allocatable is the schedulable capacity the broker reports for this pool.
	Allocatable *corev1.ResourceList `json:"allocatable,omitempty"`
	// Lease is the broker heartbeat; a stale RenewTime drives Phase to Unknown.
	Lease *ClusterPoolLeaseApplyConfiguration `json:"lease,omitempty"`
}

// ClusterPoolStatusApplyConfiguration constructs a declarative configuration of the ClusterPoolStatus type for use with
// apply.
func ClusterPoolStatus() *ClusterPoolStatusApplyConfiguration {
	return &ClusterPoolStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ClusterPoolStatusApplyConfiguration) WithPhase(value string) *ClusterPoolStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterPoolStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterPoolStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAllocatable sets the Allocatable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allocatable field is set to the value of the last call.
func (b *ClusterPoolStatusApplyConfiguration) WithAllocatable(value corev1.ResourceList) *ClusterPoolStatusApplyConfiguration {
	b.Allocatable = &value
	return b
}

// WithLease sets the Lease field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lease field is set to the value of the last call.
func (b *ClusterPoolStatusApplyConfiguration) WithLease(value *ClusterPoolLeaseApplyConfiguration) *ClusterPoolStatusApplyConfiguration {
	b.Lease = value
	return b
}
