// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterPoolStatusApplyConfiguration represents a declarative configuration of the ClusterPoolStatus type for use
// with apply.
//
// ClusterPoolStatus defines the observed state of a ClusterPool.
type ClusterPoolStatusApplyConfiguration struct {
	// Phase is the current lifecycle phase of the ClusterPool.
	Phase *string `json:"phase,omitempty"`
	// Conditions represent the latest available observations of the ClusterPool's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ClusterPoolStatusApplyConfiguration constructs a declarative configuration of the ClusterPoolStatus type for use with
// apply.
func ClusterPoolStatus() *ClusterPoolStatusApplyConfiguration {
	return &ClusterPoolStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ClusterPoolStatusApplyConfiguration) WithPhase(value string) *ClusterPoolStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterPoolStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterPoolStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
