// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompiledWorkloadStatusApplyConfiguration represents a declarative configuration of the CompiledWorkloadStatus type for use
// with apply.
//
// CompiledWorkloadStatus defines the observed state of a CompiledWorkload.
type CompiledWorkloadStatusApplyConfiguration struct {
	// Phase is the current lifecycle phase of the CompiledWorkload.
	Phase *string `json:"phase,omitempty"`
}

// CompiledWorkloadStatusApplyConfiguration constructs a declarative configuration of the CompiledWorkloadStatus type for use with
// apply.
func CompiledWorkloadStatus() *CompiledWorkloadStatusApplyConfiguration {
	return &CompiledWorkloadStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CompiledWorkloadStatusApplyConfiguration) WithPhase(value string) *CompiledWorkloadStatusApplyConfiguration {
	b.Phase = &value
	return b
}
