// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NodeDrainStatusApplyConfiguration represents a declarative configuration of the NodeDrainStatus type for use
// with apply.
//
// NodeDrainStatus is the per-/64 drain confirmation used to gate fence release.
type NodeDrainStatusApplyConfiguration struct {
	// Prefix is the node /64 underlay prefix.
	Prefix *string `json:"prefix,omitempty"`
	// Drained is true once the broker confirms the /64's stale VMIs are gone.
	Drained *bool `json:"drained,omitempty"`
}

// NodeDrainStatusApplyConfiguration constructs a declarative configuration of the NodeDrainStatus type for use with
// apply.
func NodeDrainStatus() *NodeDrainStatusApplyConfiguration {
	return &NodeDrainStatusApplyConfiguration{}
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *NodeDrainStatusApplyConfiguration) WithPrefix(value string) *NodeDrainStatusApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithDrained sets the Drained field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Drained field is set to the value of the last call.
func (b *NodeDrainStatusApplyConfiguration) WithDrained(value bool) *NodeDrainStatusApplyConfiguration {
	b.Drained = &value
	return b
}
