// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	compiledv1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CompiledVolumeAttachmentLister helps list CompiledVolumeAttachments.
// All objects returned here must be treated as read-only.
type CompiledVolumeAttachmentLister interface {
	// List lists all CompiledVolumeAttachments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledVolumeAttachment, err error)
	// CompiledVolumeAttachments returns an object that can list and get CompiledVolumeAttachments.
	CompiledVolumeAttachments(namespace string) CompiledVolumeAttachmentNamespaceLister
	CompiledVolumeAttachmentListerExpansion
}

// compiledVolumeAttachmentLister implements the CompiledVolumeAttachmentLister interface.
type compiledVolumeAttachmentLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledVolumeAttachment]
}

// NewCompiledVolumeAttachmentLister returns a new CompiledVolumeAttachmentLister.
func NewCompiledVolumeAttachmentLister(indexer cache.Indexer) CompiledVolumeAttachmentLister {
	return &compiledVolumeAttachmentLister{listers.New[*compiledv1alpha1.CompiledVolumeAttachment](indexer, compiledv1alpha1.Resource("compiledvolumeattachment"))}
}

// CompiledVolumeAttachments returns an object that can list and get CompiledVolumeAttachments.
func (s *compiledVolumeAttachmentLister) CompiledVolumeAttachments(namespace string) CompiledVolumeAttachmentNamespaceLister {
	return compiledVolumeAttachmentNamespaceLister{listers.NewNamespaced[*compiledv1alpha1.CompiledVolumeAttachment](s.ResourceIndexer, namespace)}
}

// CompiledVolumeAttachmentNamespaceLister helps list and get CompiledVolumeAttachments.
// All objects returned here must be treated as read-only.
type CompiledVolumeAttachmentNamespaceLister interface {
	// List lists all CompiledVolumeAttachments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledVolumeAttachment, err error)
	// Get retrieves the CompiledVolumeAttachment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*compiledv1alpha1.CompiledVolumeAttachment, error)
	CompiledVolumeAttachmentNamespaceListerExpansion
}

// compiledVolumeAttachmentNamespaceLister implements the CompiledVolumeAttachmentNamespaceLister
// interface.
type compiledVolumeAttachmentNamespaceLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledVolumeAttachment]
}
