// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	compiledv1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CompiledNICLister helps list CompiledNICs.
// All objects returned here must be treated as read-only.
type CompiledNICLister interface {
	// List lists all CompiledNICs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledNIC, err error)
	// CompiledNICs returns an object that can list and get CompiledNICs.
	CompiledNICs(namespace string) CompiledNICNamespaceLister
	CompiledNICListerExpansion
}

// compiledNICLister implements the CompiledNICLister interface.
type compiledNICLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledNIC]
}

// NewCompiledNICLister returns a new CompiledNICLister.
func NewCompiledNICLister(indexer cache.Indexer) CompiledNICLister {
	return &compiledNICLister{listers.New[*compiledv1alpha1.CompiledNIC](indexer, compiledv1alpha1.Resource("compilednic"))}
}

// CompiledNICs returns an object that can list and get CompiledNICs.
func (s *compiledNICLister) CompiledNICs(namespace string) CompiledNICNamespaceLister {
	return compiledNICNamespaceLister{listers.NewNamespaced[*compiledv1alpha1.CompiledNIC](s.ResourceIndexer, namespace)}
}

// CompiledNICNamespaceLister helps list and get CompiledNICs.
// All objects returned here must be treated as read-only.
type CompiledNICNamespaceLister interface {
	// List lists all CompiledNICs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledNIC, err error)
	// Get retrieves the CompiledNIC from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*compiledv1alpha1.CompiledNIC, error)
	CompiledNICNamespaceListerExpansion
}

// compiledNICNamespaceLister implements the CompiledNICNamespaceLister
// interface.
type compiledNICNamespaceLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledNIC]
}
