// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	compiledv1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CompiledContainerLister helps list CompiledContainers.
// All objects returned here must be treated as read-only.
type CompiledContainerLister interface {
	// List lists all CompiledContainers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledContainer, err error)
	// CompiledContainers returns an object that can list and get CompiledContainers.
	CompiledContainers(namespace string) CompiledContainerNamespaceLister
	CompiledContainerListerExpansion
}

// compiledContainerLister implements the CompiledContainerLister interface.
type compiledContainerLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledContainer]
}

// NewCompiledContainerLister returns a new CompiledContainerLister.
func NewCompiledContainerLister(indexer cache.Indexer) CompiledContainerLister {
	return &compiledContainerLister{listers.New[*compiledv1alpha1.CompiledContainer](indexer, compiledv1alpha1.Resource("compiledcontainer"))}
}

// CompiledContainers returns an object that can list and get CompiledContainers.
func (s *compiledContainerLister) CompiledContainers(namespace string) CompiledContainerNamespaceLister {
	return compiledContainerNamespaceLister{listers.NewNamespaced[*compiledv1alpha1.CompiledContainer](s.ResourceIndexer, namespace)}
}

// CompiledContainerNamespaceLister helps list and get CompiledContainers.
// All objects returned here must be treated as read-only.
type CompiledContainerNamespaceLister interface {
	// List lists all CompiledContainers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*compiledv1alpha1.CompiledContainer, err error)
	// Get retrieves the CompiledContainer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*compiledv1alpha1.CompiledContainer, error)
	CompiledContainerNamespaceListerExpansion
}

// compiledContainerNamespaceLister implements the CompiledContainerNamespaceLister
// interface.
type compiledContainerNamespaceLister struct {
	listers.ResourceIndexer[*compiledv1alpha1.CompiledContainer]
}
