// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	platformv1alpha1 "github.com/trevex/ectobase/api/platform/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RouteBusIdentityLister helps list RouteBusIdentities.
// All objects returned here must be treated as read-only.
type RouteBusIdentityLister interface {
	// List lists all RouteBusIdentities in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*platformv1alpha1.RouteBusIdentity, err error)
	// Get retrieves the RouteBusIdentity from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*platformv1alpha1.RouteBusIdentity, error)
	RouteBusIdentityListerExpansion
}

// routeBusIdentityLister implements the RouteBusIdentityLister interface.
type routeBusIdentityLister struct {
	listers.ResourceIndexer[*platformv1alpha1.RouteBusIdentity]
}

// NewRouteBusIdentityLister returns a new RouteBusIdentityLister.
func NewRouteBusIdentityLister(indexer cache.Indexer) RouteBusIdentityLister {
	return &routeBusIdentityLister{listers.New[*platformv1alpha1.RouteBusIdentity](indexer, platformv1alpha1.Resource("routebusidentity"))}
}
