// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	platformv1alpha1 "github.com/trevex/ectobase/api/platform/v1alpha1"
	compiledv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/compiled/v1alpha1"
	internal "github.com/trevex/ectobase/central/client-go/applyconfigurations/internal"
	applyconfigurationsnetv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/net/v1alpha1"
	applyconfigurationsplatformv1alpha1 "github.com/trevex/ectobase/central/client-go/applyconfigurations/platform/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=compiled.ectobase.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledContainer"):
		return &compiledv1alpha1.CompiledContainerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledContainerInterface"):
		return &compiledv1alpha1.CompiledContainerInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledContainerSpec"):
		return &compiledv1alpha1.CompiledContainerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledContainerStatus"):
		return &compiledv1alpha1.CompiledContainerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledFirewall"):
		return &compiledv1alpha1.CompiledFirewallApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledFwRule"):
		return &compiledv1alpha1.CompiledFwRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledLB"):
		return &compiledv1alpha1.CompiledLBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledLBPort"):
		return &compiledv1alpha1.CompiledLBPortApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledNATSource"):
		return &compiledv1alpha1.CompiledNATSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledNIC"):
		return &compiledv1alpha1.CompiledNICApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledNICSpec"):
		return &compiledv1alpha1.CompiledNICSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledNICStatus"):
		return &compiledv1alpha1.CompiledNICStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledPeerImport"):
		return &compiledv1alpha1.CompiledPeerImportApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVM"):
		return &compiledv1alpha1.CompiledVMApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVMInterface"):
		return &compiledv1alpha1.CompiledVMInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVMSpec"):
		return &compiledv1alpha1.CompiledVMSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVMStatus"):
		return &compiledv1alpha1.CompiledVMStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVolumeAttachment"):
		return &compiledv1alpha1.CompiledVolumeAttachmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVolumeAttachmentSpec"):
		return &compiledv1alpha1.CompiledVolumeAttachmentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CompiledVolumeAttachmentStatus"):
		return &compiledv1alpha1.CompiledVolumeAttachmentStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PortStatus"):
		return &compiledv1alpha1.PortStatusApplyConfiguration{}

		// Group=net.ectobase.dev, Version=v1alpha1
	case netv1alpha1.SchemeGroupVersion.WithKind("Container"):
		return &applyconfigurationsnetv1alpha1.ContainerApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("ContainerSpec"):
		return &applyconfigurationsnetv1alpha1.ContainerSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("ContainerStatus"):
		return &applyconfigurationsnetv1alpha1.ContainerStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("EgressQoS"):
		return &applyconfigurationsnetv1alpha1.EgressQoSApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("FirewallPolicy"):
		return &applyconfigurationsnetv1alpha1.FirewallPolicyApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("FirewallPolicyRule"):
		return &applyconfigurationsnetv1alpha1.FirewallPolicyRuleApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("FirewallPolicySpec"):
		return &applyconfigurationsnetv1alpha1.FirewallPolicySpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("FloatingIP"):
		return &applyconfigurationsnetv1alpha1.FloatingIPApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("InterfaceQoS"):
		return &applyconfigurationsnetv1alpha1.InterfaceQoSApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("LoadBalancer"):
		return &applyconfigurationsnetv1alpha1.LoadBalancerApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("LoadBalancerPort"):
		return &applyconfigurationsnetv1alpha1.LoadBalancerPortApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("LoadBalancerSpec"):
		return &applyconfigurationsnetv1alpha1.LoadBalancerSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("LoadBalancerStatus"):
		return &applyconfigurationsnetv1alpha1.LoadBalancerStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("LocalObjectReference"):
		return &applyconfigurationsnetv1alpha1.LocalObjectReferenceApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NATAllocation"):
		return &applyconfigurationsnetv1alpha1.NATAllocationApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NATGateway"):
		return &applyconfigurationsnetv1alpha1.NATGatewayApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NATGatewaySpec"):
		return &applyconfigurationsnetv1alpha1.NATGatewaySpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NATGatewayStatus"):
		return &applyconfigurationsnetv1alpha1.NATGatewayStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NetworkInterface"):
		return &applyconfigurationsnetv1alpha1.NetworkInterfaceApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NetworkInterfaceSpec"):
		return &applyconfigurationsnetv1alpha1.NetworkInterfaceSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("NetworkInterfaceStatus"):
		return &applyconfigurationsnetv1alpha1.NetworkInterfaceStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("PortStatus"):
		return &applyconfigurationsnetv1alpha1.PortStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("RateLimit"):
		return &applyconfigurationsnetv1alpha1.RateLimitApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VirtualMachine"):
		return &applyconfigurationsnetv1alpha1.VirtualMachineApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VirtualMachineSpec"):
		return &applyconfigurationsnetv1alpha1.VirtualMachineSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VirtualMachineStatus"):
		return &applyconfigurationsnetv1alpha1.VirtualMachineStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VMAntiAffinity"):
		return &applyconfigurationsnetv1alpha1.VMAntiAffinityApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VMPlacement"):
		return &applyconfigurationsnetv1alpha1.VMPlacementApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("Volume"):
		return &applyconfigurationsnetv1alpha1.VolumeApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VolumeSpec"):
		return &applyconfigurationsnetv1alpha1.VolumeSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VolumeStatus"):
		return &applyconfigurationsnetv1alpha1.VolumeStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPC"):
		return &applyconfigurationsnetv1alpha1.VPCApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCPeering"):
		return &applyconfigurationsnetv1alpha1.VPCPeeringApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCPeeringSpec"):
		return &applyconfigurationsnetv1alpha1.VPCPeeringSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCPeeringStatus"):
		return &applyconfigurationsnetv1alpha1.VPCPeeringStatusApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCReference"):
		return &applyconfigurationsnetv1alpha1.VPCReferenceApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCSpec"):
		return &applyconfigurationsnetv1alpha1.VPCSpecApplyConfiguration{}
	case netv1alpha1.SchemeGroupVersion.WithKind("VPCStatus"):
		return &applyconfigurationsnetv1alpha1.VPCStatusApplyConfiguration{}

		// Group=platform.ectobase.dev, Version=v1alpha1
	case platformv1alpha1.SchemeGroupVersion.WithKind("ClusterPool"):
		return &applyconfigurationsplatformv1alpha1.ClusterPoolApplyConfiguration{}
	case platformv1alpha1.SchemeGroupVersion.WithKind("ClusterPoolLease"):
		return &applyconfigurationsplatformv1alpha1.ClusterPoolLeaseApplyConfiguration{}
	case platformv1alpha1.SchemeGroupVersion.WithKind("ClusterPoolSpec"):
		return &applyconfigurationsplatformv1alpha1.ClusterPoolSpecApplyConfiguration{}
	case platformv1alpha1.SchemeGroupVersion.WithKind("ClusterPoolStatus"):
		return &applyconfigurationsplatformv1alpha1.ClusterPoolStatusApplyConfiguration{}
	case platformv1alpha1.SchemeGroupVersion.WithKind("NodeDrainStatus"):
		return &applyconfigurationsplatformv1alpha1.NodeDrainStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
