// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPools implements IPPoolInterface
type fakeIPPools struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IPPool, *v1alpha1.IPPoolList, *netv1alpha1.IPPoolApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeIPPools(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.IPPoolInterface {
	return &fakeIPPools{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IPPool, *v1alpha1.IPPoolList, *netv1alpha1.IPPoolApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ippools"),
			v1alpha1.SchemeGroupVersion.WithKind("IPPool"),
			func() *v1alpha1.IPPool { return &v1alpha1.IPPool{} },
			func() *v1alpha1.IPPoolList { return &v1alpha1.IPPoolList{} },
			func(dst, src *v1alpha1.IPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPPoolList) []*v1alpha1.IPPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPPoolList, items []*v1alpha1.IPPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
