// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVPCPeerings implements VPCPeeringInterface
type fakeVPCPeerings struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.VPCPeering, *v1alpha1.VPCPeeringList, *netv1alpha1.VPCPeeringApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeVPCPeerings(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.VPCPeeringInterface {
	return &fakeVPCPeerings{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.VPCPeering, *v1alpha1.VPCPeeringList, *netv1alpha1.VPCPeeringApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("vpcpeerings"),
			v1alpha1.SchemeGroupVersion.WithKind("VPCPeering"),
			func() *v1alpha1.VPCPeering { return &v1alpha1.VPCPeering{} },
			func() *v1alpha1.VPCPeeringList { return &v1alpha1.VPCPeeringList{} },
			func(dst, src *v1alpha1.VPCPeeringList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VPCPeeringList) []*v1alpha1.VPCPeering { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VPCPeeringList, items []*v1alpha1.VPCPeering) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
