// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/trevex/ectobase/api/net/v1alpha1"
	netv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/net/v1alpha1"
	typednetv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/typed/net/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnets implements SubnetInterface
type fakeSubnets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Subnet, *v1alpha1.SubnetList, *netv1alpha1.SubnetApplyConfiguration]
	Fake *FakeNetV1alpha1
}

func newFakeSubnets(fake *FakeNetV1alpha1, namespace string) typednetv1alpha1.SubnetInterface {
	return &fakeSubnets{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Subnet, *v1alpha1.SubnetList, *netv1alpha1.SubnetApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnets"),
			v1alpha1.SchemeGroupVersion.WithKind("Subnet"),
			func() *v1alpha1.Subnet { return &v1alpha1.Subnet{} },
			func() *v1alpha1.SubnetList { return &v1alpha1.SubnetList{} },
			func(dst, src *v1alpha1.SubnetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetList) []*v1alpha1.Subnet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SubnetList, items []*v1alpha1.Subnet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
