[package]
name = "flowplane-node"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
flowplane-common = { path = "../flowplane-common" }
flowplane-control = { path = "../flowplane-control" }
tonic = { workspace = true }
prost = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
flowplane-control = { path = "../flowplane-control", features = ["mem-writer"] }

[build-dependencies]
tonic-build = "0.12"
