// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	compiledv1alpha1 "github.com/trevex/ectobase/api/compiled/v1alpha1"
	applyconfigurationscompiledv1alpha1 "github.com/trevex/ectobase/dispatch/client-go/applyconfigurations/compiled/v1alpha1"
	scheme "github.com/trevex/ectobase/dispatch/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CompiledVolumeAttachmentsGetter has a method to return a CompiledVolumeAttachmentInterface.
// A group's client should implement this interface.
type CompiledVolumeAttachmentsGetter interface {
	CompiledVolumeAttachments(namespace string) CompiledVolumeAttachmentInterface
}

// CompiledVolumeAttachmentInterface has methods to work with CompiledVolumeAttachment resources.
type CompiledVolumeAttachmentInterface interface {
	Create(ctx context.Context, compiledVolumeAttachment *compiledv1alpha1.CompiledVolumeAttachment, opts v1.CreateOptions) (*compiledv1alpha1.CompiledVolumeAttachment, error)
	Update(ctx context.Context, compiledVolumeAttachment *compiledv1alpha1.CompiledVolumeAttachment, opts v1.UpdateOptions) (*compiledv1alpha1.CompiledVolumeAttachment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compiledVolumeAttachment *compiledv1alpha1.CompiledVolumeAttachment, opts v1.UpdateOptions) (*compiledv1alpha1.CompiledVolumeAttachment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*compiledv1alpha1.CompiledVolumeAttachment, error)
	List(ctx context.Context, opts v1.ListOptions) (*compiledv1alpha1.CompiledVolumeAttachmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *compiledv1alpha1.CompiledVolumeAttachment, err error)
	Apply(ctx context.Context, compiledVolumeAttachment *applyconfigurationscompiledv1alpha1.CompiledVolumeAttachmentApplyConfiguration, opts v1.ApplyOptions) (result *compiledv1alpha1.CompiledVolumeAttachment, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, compiledVolumeAttachment *applyconfigurationscompiledv1alpha1.CompiledVolumeAttachmentApplyConfiguration, opts v1.ApplyOptions) (result *compiledv1alpha1.CompiledVolumeAttachment, err error)
	CompiledVolumeAttachmentExpansion
}

// compiledVolumeAttachments implements CompiledVolumeAttachmentInterface
type compiledVolumeAttachments struct {
	*gentype.ClientWithListAndApply[*compiledv1alpha1.CompiledVolumeAttachment, *compiledv1alpha1.CompiledVolumeAttachmentList, *applyconfigurationscompiledv1alpha1.CompiledVolumeAttachmentApplyConfiguration]
}

// newCompiledVolumeAttachments returns a CompiledVolumeAttachments
func newCompiledVolumeAttachments(c *CompiledV1alpha1Client, namespace string) *compiledVolumeAttachments {
	return &compiledVolumeAttachments{
		gentype.NewClientWithListAndApply[*compiledv1alpha1.CompiledVolumeAttachment, *compiledv1alpha1.CompiledVolumeAttachmentList, *applyconfigurationscompiledv1alpha1.CompiledVolumeAttachmentApplyConfiguration](
			"compiledvolumeattachments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *compiledv1alpha1.CompiledVolumeAttachment { return &compiledv1alpha1.CompiledVolumeAttachment{} },
			func() *compiledv1alpha1.CompiledVolumeAttachmentList {
				return &compiledv1alpha1.CompiledVolumeAttachmentList{}
			},
		),
	}
}
