// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type CompiledContainerExpansion interface{}

type CompiledNICExpansion interface{}

type CompiledVMExpansion interface{}

type CompiledVolumeAttachmentExpansion interface{}
